import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const descriptions = {
  // ═══ INDIA ═══
  138: { es: 'Pollo en salsa cremosa de tomate con mantequilla, crema y especias suaves como garam masala, cardamomo y fenogreco. El plato que conquistó el mundo desde los tandoors de Delhi.', en: 'Chicken in a creamy tomato sauce with butter, cream and mild spices like garam masala, cardamom and fenugreek. The dish that conquered the world from Delhi\'s tandoors.' },
  139: { es: 'Trozos de pollo marinados en yogur y especias, asados al tandoor y servidos en una salsa cremosa de tomate con garam masala. Nacido en Glasgow, perfeccionado globalmente.', en: 'Chicken pieces marinated in yogurt and spices, tandoor-roasted and served in a creamy tomato sauce with garam masala. Born in Glasgow, perfected globally.' },
  140: { es: 'Arroz basmati perfumado con azafrán y especias enteras, cocinado en capas con cordero tierno marinado en yogur. Sellado y cocido al dum hasta que los aromas se fusionan.', en: 'Saffron-scented basmati rice with whole spices, layered with tender lamb marinated in yogurt. Sealed and dum-cooked until the aromas meld together.' },
  141: { es: 'Cubos de paneer (queso indio) flotando en una salsa vibrante de espinacas frescas con ajo, jengibre y garam masala. Vegetariano, nutritivo y lleno de sabor.', en: 'Paneer (Indian cheese) cubes floating in a vibrant fresh spinach sauce with garlic, ginger and garam masala. Vegetarian, nutritious and full of flavor.' },
  142: { es: 'Triángulos de masa crujiente rellenos de papa especiada con chícharos, cilantro y comino, fritos hasta dorar. El snack callejero indio que se come con chutney de menta.', en: 'Crispy dough triangles filled with spiced potato, peas, cilantro and cumin, fried until golden. The Indian street snack eaten with mint chutney.' },
  143: { es: 'Bolitas de leche en polvo y harina fritas, empapadas en almíbar perfumado con cardamomo y agua de rosas. Dulces, esponjosos y empapados — el postre indio más festivo.', en: 'Fried balls of milk powder and flour soaked in cardamom and rose water syrup. Sweet, spongy and syrup-soaked — India\'s most festive dessert.' },
  144: { es: 'Bebida refrescante de yogur batido con pulpa de mango fresco, azúcar y un toque de cardamomo. Cremoso, dulce y tropical — el smoothie indio perfecto para el calor.', en: 'Refreshing drink of yogurt blended with fresh mango pulp, sugar and a touch of cardamom. Creamy, sweet and tropical — the perfect Indian smoothie for the heat.' },
  145: { es: 'Pollo marinado en yogur, pasta de chile de Cachemira, jengibre y garam masala, asado en horno tandoor a 480°C. Exterior carbonizado, interior jugoso y rojo brillante.', en: 'Chicken marinated in yogurt, Kashmiri chili paste, ginger and garam masala, roasted in a tandoor oven at 900°F. Charred exterior, juicy and bright red inside.' },
  146: { es: 'Cordero cocido lentamente en salsa de yogur con chiles de Cachemira, cardamomo, clavo y canela. Guiso aromático y profundo de la cocina mogol de Cachemira.', en: 'Lamb slow-cooked in yogurt sauce with Kashmiri chiles, cardamom, cloves and cinnamon. Deep aromatic stew from the Mughal cuisine of Kashmir.' },
  147: { es: 'Garbanzos cocidos en salsa espesa de tomate con cebolla caramelizada, jengibre, ajo y especias como amchur y garam masala. Proteína vegetal con sabor intenso del norte de India.', en: 'Chickpeas simmered in thick tomato sauce with caramelized onion, ginger, garlic and spices like amchur and garam masala. Plant protein with intense flavor from northern India.' },
  148: { es: 'Lentejas negras (urad dal) cocidas toda la noche a fuego lento con mantequilla, crema, tomate y especias. Cremosa y ahumada — la reina de los dals del Punjab.', en: 'Black lentils (urad dal) simmered overnight with butter, cream, tomato and spices. Creamy and smoky — the queen of Punjab\'s dals.' },
  149: { es: 'Coliflor y papa cocidas en seco con cúrcuma, comino, cilantro y chile verde. Un clásico vegetariano del norte de India — sencillo, reconfortante y aromático.', en: 'Cauliflower and potato dry-cooked with turmeric, cumin, coriander and green chile. A vegetarian classic from northern India — simple, comforting and aromatic.' },

  // ═══ THAILAND ═══
  150: { es: 'Fideos de arroz salteados al wok con salsa de tamarindo, salsa de pescado, azúcar de palma, huevo, brotes de soya, cacahuates y camarones secos. El plato nacional tailandés.', en: 'Rice noodles wok-fried with tamarind sauce, fish sauce, palm sugar, egg, bean sprouts, peanuts and dried shrimp. Thailand\'s national dish.' },
  151: { es: 'Curry de pasta verde hecho con chiles verdes, hierba limón, galanga y albahaca tailandesa en leche de coco. Picante, fragante y herbáceo — Tailandia en un bol.', en: 'Green curry paste made with green chiles, lemongrass, galangal and Thai basil in coconut milk. Spicy, fragrant and herbal — Thailand in a bowl.' },
  153: { es: 'Arroz glutinoso cocido al vapor e impregnado en leche de coco dulce, servido con láminas de mango maduro y semillas de sésamo. El postre tailandés más icónico.', en: 'Steamed glutinous rice soaked in sweet coconut milk, served with ripe mango slices and sesame seeds. Thailand\'s most iconic dessert.' },
  154: { es: 'Ensalada tailandesa de papaya verde rallada machacada en mortero con tomates cherry, ejotes, cacahuates, chile, limón y salsa de pescado. Crujiente, ácida y explosivamente picante.', en: 'Thai salad of shredded green papaya pounded in a mortar with cherry tomatoes, green beans, peanuts, chile, lime and fish sauce. Crunchy, tangy and explosively spicy.' },
  155: { es: 'Curry tailandés dulce y aromático con carne de res, papas, cacahuates tostados, leche de coco y pasta massaman con cardamomo, canela y clavo. Influencia persa en Tailandia.', en: 'Sweet, aromatic Thai curry with beef, potatoes, toasted peanuts, coconut milk and massaman paste with cardamom, cinnamon and cloves. Persian influence in Thailand.' },
  156: { es: 'Brochetas de pollo marinado en leche de coco, cúrcuma y hierba limón, asadas sobre carbón y servidas con salsa de cacahuate cremosa. Street food tailandés adictivo.', en: 'Chicken skewers marinated in coconut milk, turmeric and lemongrass, grilled over charcoal and served with creamy peanut sauce. Addictive Thai street food.' },
  157: { es: 'Carne picada de cerdo salteada al wok con chiles, ajo, albahaca santa (holy basil) y salsa de pescado, coronada con huevo frito. Comida callejera picante de Bangkok.', en: 'Minced pork stir-fried in a wok with chiles, garlic, holy basil and fish sauce, topped with a fried egg. Spicy Bangkok street food.' },
  158: { es: 'Arroz frito tailandés al wok con huevo, ajo, salsa de pescado, azúcar y un toque de limón. Simple pero perfecto con camarones, cangrejo o pollo. Cada puesto lo hace diferente.', en: 'Thai wok-fried rice with egg, garlic, fish sauce, sugar and a squeeze of lime. Simple yet perfect with shrimp, crab or chicken. Every stall makes it different.' },
  159: { es: 'Sopa cremosa de leche de coco con galanga, hierba limón, hojas de lima kaffir, champiñones y pollo. Aromática y reconfortante — la hermana suave del tom yum.', en: 'Creamy coconut milk soup with galangal, lemongrass, kaffir lime leaves, mushrooms and chicken. Aromatic and comforting — tom yum\'s gentle sibling.' },
  160: { es: 'Sopa de fideos de huevo del norte de Tailandia con curry cremoso de coco, pollo tierno y fideos crujientes encima. Influencia birmana en Chiang Mai — dulce, picante y cremoso.', en: 'Northern Thai egg noodle soup with creamy coconut curry, tender chicken and crispy noodles on top. Burmese influence in Chiang Mai — sweet, spicy and creamy.' },
  161: { es: 'Fideos de arroz anchos salteados al wok con salsa de soya oscura, huevo, brócoli chino y cerdo. Ahumados por el wok a fuego alto — el wok hei tailandés.', en: 'Wide rice noodles stir-fried in a wok with dark soy sauce, egg, Chinese broccoli and pork. Smoky from the high-heat wok — Thai wok hei.' },
  162: { es: 'Ensalada picante tailandesa de carne de cerdo picada con menta, cilantro, chalota, chile molido, limón y arroz tostado en polvo. Refrescante y explosivamente picante.', en: 'Spicy Thai salad of minced pork with mint, cilantro, shallot, ground chile, lime and toasted rice powder. Refreshing and explosively spicy.' },
  163: { es: 'Ensalada tailandesa de camarones con hierba limón fresca picada, chalotas, menta, chile y jugo de limón. Ácida, picante y fragante — frescura marina del golfo de Tailandia.', en: 'Thai shrimp salad with fresh chopped lemongrass, shallots, mint, chile and lime juice. Tangy, spicy and fragrant — ocean freshness from the Gulf of Thailand.' },
  164: { es: 'Pollo salteado al wok con anacardos tostados, chile seco, cebolla y salsa de ostión. Crujiente, dulce-salado y ligeramente picante — street food thai rápido y satisfactorio.', en: 'Chicken stir-fried in a wok with toasted cashews, dried chile, onion and oyster sauce. Crunchy, sweet-salty and mildly spicy — quick and satisfying Thai street food.' },
  284: { es: 'Sopa caliente y ácida con camarones, galanga, hierba limón, hojas de lima kaffir, chiles y jugo de limón. Picante, ácida y fragante — la sopa tailandesa que despierta los sentidos.', en: 'Hot and sour soup with shrimp, galangal, lemongrass, kaffir lime leaves, chiles and lime juice. Spicy, tangy and fragrant — the Thai soup that awakens the senses.' },
  289: { es: 'Curry tailandés espeso y cremoso con pasta de panang, leche de coco, hojas de lima kaffir y cacahuates. Más suave que el curry rojo, con un dulzor aromático profundo.', en: 'Thick, creamy Thai curry with panang paste, coconut milk, kaffir lime leaves and peanuts. Milder than red curry, with a deep aromatic sweetness.' },
  290: { es: 'Pasteles de pescado tailandeses moldeados a mano con pasta de curry rojo, ejotes picados y hojas de lima kaffir, fritos hasta dorar. Elásticos y aromáticos con salsa de pepino.', en: 'Thai fish cakes hand-molded with red curry paste, chopped green beans and kaffir lime leaves, fried until golden. Springy and aromatic with cucumber sauce.' },
  291: { es: 'Ensalada tailandesa de carne de res a la parrilla cortada fina, con menta, cilantro, cebolla, chile, limón y arroz tostado. Fresca, picante y llena de texturas.', en: 'Thai grilled beef salad sliced thin, with mint, cilantro, onion, chile, lime and toasted rice. Fresh, spicy and full of textures.' },

  // ═══ GREECE ═══
  89: { es: 'Ensalada griega clásica con tomate, pepino, cebolla morada, aceitunas kalamata y un bloque de queso feta, aliñada solo con aceite de oliva y orégano. Mediterráneo puro.', en: 'Classic Greek salad with tomato, cucumber, red onion, kalamata olives and a block of feta cheese, dressed with just olive oil and oregano. Pure Mediterranean.' },
  165: { es: 'Capas de berenjena frita, carne picada de cordero con tomate y canela, coronadas con bechamel espesa y gratinada. El lasagna griego — sustancioso y reconfortante.', en: 'Layers of fried eggplant, ground lamb with tomato and cinnamon, topped with thick gratinated béchamel. The Greek lasagna — hearty and comforting.' },
  167: { es: 'Tiras de pollo marinado en yogur, orégano y limón, asadas al grill y servidas en pan pita con tzatziki, tomate, cebolla y papas fritas. Street food de Atenas.', en: 'Chicken strips marinated in yogurt, oregano and lemon, grilled and served in pita bread with tzatziki, tomato, onion and fries. Athens street food.' },
  168: { es: 'Capas de masa filo crujiente con nueces y pistachos triturados, bañadas en almíbar perfumado con miel y agua de rosas. Dulce, crujiente y pegajoso — herencia otomana.', en: 'Layers of crispy phyllo dough with crushed walnuts and pistachios, soaked in syrup perfumed with honey and rose water. Sweet, crunchy and sticky — Ottoman heritage.' },
  169: { es: 'Triángulos de masa filo crujiente rellenos de espinacas frescas, queso feta desmenuzado, eneldo y cebolleta. Dorados al horno — el snack griego de toda abuela.', en: 'Crispy phyllo dough triangles filled with fresh spinach, crumbled feta cheese, dill and scallion. Baked golden — every Greek grandmother\'s snack.' },
  170: { es: 'Hojas de parra rellenas de arroz con hierbas, piñones, menta y eneldo, cocidas lentamente con limón y aceite de oliva. Bocados mediterráneos envueltos en verde.', en: 'Grape leaves stuffed with herbed rice, pine nuts, mint and dill, slowly cooked with lemon and olive oil. Mediterranean bites wrapped in green.' },
  171: { es: 'Salsa griega espesa de yogur colado con pepino rallado, ajo, eneldo, aceite de oliva y limón. Fresca y cremosa — acompaña desde gyros hasta verduras asadas.', en: 'Thick Greek sauce of strained yogurt with grated cucumber, garlic, dill, olive oil and lemon. Fresh and creamy — pairs with everything from gyros to roasted vegetables.' },
  172: { es: 'Pasta tubular horneada con ragú de carne de res y canela, cubierta con bechamel espesa y gratinada. El primo griego de la lasaña — reconfortante y especiado.', en: 'Tubular pasta baked with beef ragù and cinnamon, topped with thick béchamel and gratinated. Lasagna\'s Greek cousin — comforting and spiced.' },
  173: { es: 'Pastel griego de crema de sémola con ralladura de naranja y vainilla, envuelta en capas de masa filo mantequillosa. Bañada en almíbar de limón. Textura crujiente-cremosa.', en: 'Greek custard pie of semolina cream with orange zest and vanilla, wrapped in buttery phyllo layers. Soaked in lemon syrup. Crispy-creamy texture.' },
  174: { es: 'Albóndigas griegas de carne de cordero y res con menta, orégano, cebolla y pan remojado, fritas hasta dorar. Servidas con tzatziki frío — contraste delicioso.', en: 'Greek meatballs of lamb and beef with mint, oregano, onion and soaked bread, fried until golden. Served with cold tzatziki — delicious contrast.' },
  175: { es: 'Bloque grueso de queso graviera o kasseri rebozado en harina y frito en aceite de oliva caliente hasta que el exterior es crujiente y el interior fundido. Se flamea con ouzo y limón.', en: 'Thick block of graviera or kasseri cheese floured and fried in hot olive oil until the outside is crispy and the inside is molten. Flambéed with ouzo and lemon.' },
  176: { es: 'Tomates y pimientos vaciados y rellenos de arroz con hierbas, piñones y pasas, horneados lentamente en aceite de oliva. Plato de verano griego colorido y aromático.', en: 'Tomatoes and peppers hollowed out and stuffed with herbed rice, pine nuts and raisins, slowly baked in olive oil. Colorful and aromatic Greek summer dish.' },
  177: { es: 'Sopa griega rústica de judiones blancos con tomate, zanahoria, apio y aceite de oliva. El plato nacional griego — sencillo, nutritivo y reconfortante. Mejor al día siguiente.', en: 'Rustic Greek soup of large white beans with tomato, carrot, celery and olive oil. Greece\'s national dish — simple, nutritious and comforting. Better the next day.' },
  178: { es: 'Ternera cocida lentamente en salsa de tomate con canela y hierbas, con pasta orzo horneada hasta que absorbe todos los jugos. Guiso griego de olla a horno.', en: 'Beef slowly braised in tomato sauce with cinnamon and herbs, with orzo pasta baked until it absorbs all the juices. Greek pot-to-oven stew.' },
  292: { es: 'Brochetas de cerdo marinado en limón, orégano y aceite de oliva, asadas sobre brasas. Servidas con pita caliente, tzatziki y ensalada. El asado callejero griego.', en: 'Pork skewers marinated in lemon, oregano and olive oil, grilled over charcoal. Served with warm pita, tzatziki and salad. Greek street grilling.' },
  297: { es: 'Pierna de cordero envuelta en papel pergamino con ajo, orégano y limón, cocida lentamente durante horas hasta que la carne se deshace. "Cordero del ladrón" — estilo cretense.', en: 'Lamb leg wrapped in parchment with garlic, oregano and lemon, slowly cooked for hours until the meat falls apart. "Thief\'s lamb" — Cretan style.' },
  299: { es: 'Dip griego cremoso de huevas de pescado (tarama) batidas con pan remojado, aceite de oliva, jugo de limón y cebolla. Rosado, suave y con profundo sabor a mar.', en: 'Creamy Greek dip of fish roe (tarama) whipped with soaked bread, olive oil, lemon juice and onion. Pink, smooth and with deep ocean flavor.' },
  302: { es: 'Bolitas de masa frita esponjosas bañadas en miel caliente y espolvoreadas con canela y nueces trituradas. Los donuts griegos — crujientes por fuera, aireados por dentro.', en: 'Fluffy fried dough balls drizzled with warm honey and sprinkled with cinnamon and crushed walnuts. Greek donuts — crispy outside, airy inside.' },

  // ═══ JAPAN (extras) ═══
  242: { es: 'Fideos gruesos y elásticos de trigo en un caldo dashi caliente con soya y mirin, coronados con cebollín, kamaboko y tempura de camarón. Reconfortante bol japonés.', en: 'Thick, chewy wheat noodles in a hot dashi broth with soy and mirin, topped with scallions, kamaboko and shrimp tempura. Comforting Japanese bowl.' },
  243: { es: 'Caldo claro de dashi con pasta de miso disuelta, tofu suave, alga wakame y cebollín. La sopa que acompaña cada comida japonesa — umami puro en cada sorbo.', en: 'Clear dashi broth with dissolved miso paste, soft tofu, wakame seaweed and scallions. The soup that accompanies every Japanese meal — pure umami in every sip.' },
  248: { es: 'Tortilla japonesa enrollada en múltiples capas finas, ligeramente dulce con dashi y mirin. Suave y esponjosa — presente en cada bento box y como sushi de desayuno.', en: 'Japanese omelette rolled in multiple thin layers, slightly sweet with dashi and mirin. Soft and fluffy — found in every bento box and as breakfast sushi.' },
  249: { es: 'Flan salado japonés cocido al vapor con caldo dashi, huevo y pequeños trozos de pollo, camarón y seta shiitake. Textura sedosa y temblorosa — elegancia al vapor.', en: 'Japanese savory custard steamed with dashi broth, egg and small pieces of chicken, shrimp and shiitake mushroom. Silky, wobbly texture — steamed elegance.' },

  // ═══ MEXICO (extras) ═══
  181: { es: 'Camarones salteados en salsa de chiles guajillo, morita y de árbol bien picante con ajo y tomate. Picor intenso que arde y satisface — mariscos con fuego mexicano.', en: 'Shrimp sautéed in a fiery sauce of guajillo, morita and de árbol chiles with garlic and tomato. Intense heat that burns and satisfies — seafood with Mexican fire.' },
  182: { es: 'Cubos de pescado blanco fresco "cocidos" en jugo de limón con cebolla morada, chile, cilantro y camote. Ácido, fresco y marino — la costa peruana en un plato.', en: 'Fresh white fish cubes "cooked" in lime juice with red onion, chile, cilantro and sweet potato. Tangy, fresh and oceanic — the Peruvian coast on a plate.' },
  183: { es: 'Borrego cocido durante horas en pencas de maguey o envuelto en hojas, hasta que la carne se deshebra con los dedos. Jugosa y perfumada — la fiesta mexicana del domingo.', en: 'Lamb cooked for hours in maguey leaves or wrapped in foil, until the meat shreds with your fingers. Juicy and fragrant — Mexico\'s Sunday feast.' },
  184: { es: 'Tortillas de maíz rellenas de pollo deshebrado, enrolladas apretadas y fritas hasta quedar crujientes. Servidas con crema, lechuga, salsa verde y queso fresco.', en: 'Corn tortillas filled with shredded chicken, rolled tightly and fried until crispy. Served with cream, lettuce, green salsa and fresh cheese.' },
  185: { es: 'Huevos estrellados sobre tortilla de maíz frita, bañados en salsa roja o verde picante, con frijoles refritos al lado. El desayuno mexicano que te levanta de cualquier cruda.', en: 'Fried eggs on a fried corn tortilla, bathed in spicy red or green salsa, with refried beans on the side. The Mexican breakfast that cures any hangover.' },
  186: { es: 'Caldo rojo intenso de estómago de res (pancita) cocido durante horas con chiles guajillo y ancho, orégano y cebolla. Se come con limón, orégano y chile. Medicina mexicana.', en: 'Intense red broth of beef tripe (honeycomb) simmered for hours with guajillo and ancho chiles, oregano and onion. Eaten with lime, oregano and chile. Mexican medicine.' },
  187: { es: 'Tortillas de maíz hechas a mano rellenas de queso Oaxaca derretido, cocinadas en comal hasta quedar crujientes. Se comen con epazote, flor de calabaza y salsa.', en: 'Handmade corn tortillas filled with melted Oaxaca cheese, cooked on a comal until crispy. Eaten with epazote, squash blossom and salsa.' },
  188: { es: 'Tortilla de maíz gigante y crujiente de Oaxaca cubierta con frijoles negros, asiento (grasa de cerdo), tasajo o cecina, quesillo, lechuga y salsa. La pizza mexicana oaxaqueña.', en: 'Giant crispy Oaxacan corn tortilla topped with black beans, pork fat drippings, jerky or cured meat, string cheese, lettuce and salsa. The Oaxacan Mexican pizza.' },

  // ═══ USA (extras) ═══
  214: { es: 'Costillas de cerdo ahumadas lentamente a baja temperatura con madera de roble o nogal, barnizadas con salsa BBQ dulce y ahumada. Se caen del hueso — tradición sureña.', en: 'Pork ribs slowly smoked at low temperature over oak or hickory wood, glazed with sweet and smoky BBQ sauce. Fall-off-the-bone — Southern tradition.' },
  218: { es: 'Sopa cremosa de almejas con papa, tocino, cebolla y crema espesa en un bol de pan sourdough. El plato que calienta los inviernos de Nueva Inglaterra desde el siglo XVIII.', en: 'Creamy clam chowder with potato, bacon, onion and heavy cream in a sourdough bread bowl. The dish that warms New England winters since the 18th century.' },
  219: { es: 'Arroz cajún cocido en un solo sartén con salchicha andouille, camarones, pollo y la "santísima trinidad" de Louisiana: apio, pimiento y cebolla. Sabor del bayou.', en: 'Cajun rice cooked in one pan with andouille sausage, shrimp, chicken and Louisiana\'s "holy trinity": celery, bell pepper and onion. Bayou flavor.' },
  221: { es: 'Salchicha de res en pan suave cubierta con mostaza amarilla, chucrut, salsa de tomate y cebolla crujiente frita. El hot dog neoyorquino de los carritos callejeros.', en: 'Beef frankfurter in a soft bun topped with yellow mustard, sauerkraut, tomato sauce and crispy fried onions. The New York hot dog from street carts.' },
  223: { es: 'Pancakes esponjosos y gruesos apilados con mantequilla derretida y maple syrup real, acompañados de tocino crujiente. El desayuno americano clásico de los diners.', en: 'Thick fluffy pancakes stacked with melted butter and real maple syrup, served with crispy bacon. The classic American diner breakfast.' },
  224: { es: 'Ensalada abundante con pollo, tocino crujiente, huevo duro, aguacate, queso azul, tomate y maíz, todo en filas ordenadas sobre lechuga. Nacida en el Hollywood Brown Derby en 1937.', en: 'Hearty salad with chicken, crispy bacon, hard-boiled egg, avocado, blue cheese, tomato and corn, all in neat rows over lettuce. Born at the Hollywood Brown Derby in 1937.' },
  225: { es: 'Pan de carne molida mezclada con cebolla, pan rallado, huevo y ketchup, horneado en forma de barra con glaseado de ketchup dulce. Comfort food americano que sabe a hogar.', en: 'Ground beef loaf mixed with onion, breadcrumbs, egg and ketchup, baked in a loaf shape with sweet ketchup glaze. American comfort food that tastes like home.' },
  227: { es: 'Pay de manzanas Granny Smith especiadas con canela y nuez moscada entre dos capas de masa mantequillosa y dorada. El postre que define a América — mejor con helado de vainilla.', en: 'Granny Smith apple pie spiced with cinnamon and nutmeg between two layers of buttery golden crust. The dessert that defines America — best with vanilla ice cream.' },
  229: { es: 'Brownies densos y fudgy de chocolate oscuro con centro húmedo y costra crackelada. No son pastel — son chocolate concentrado en forma cuadrada. Irresistibles tibios.', en: 'Dense, fudgy dark chocolate brownies with a moist center and crackled crust. Not cake — concentrated chocolate in square form. Irresistible when warm.' },
  230: { es: 'Pan de maíz esponjoso y ligeramente dulce, horneado en sartén de hierro hasta que la costra queda dorada y crujiente. Acompañante del BBQ y del chili del sur americano.', en: 'Fluffy, slightly sweet cornbread baked in a cast iron skillet until the crust is golden and crispy. The companion to BBQ and chili from the American South.' },

  // ═══ CHINA (extras) ═══
  281: { es: 'Caldo cristalino de pollo con dumplings de masa fina rellenos de cerdo y camarones picados con jengibre. Los wontons flotan como nubes — sopa reconfortante cantonesa.', en: 'Crystal-clear chicken broth with thin-skinned dumplings filled with minced pork and shrimp with ginger. Wontons float like clouds — comforting Cantonese soup.' },
  283: { es: 'Pasteles redondos de masa con relleno de pasta de semilla de loto o yema de huevo salada, decorados con sellos en relieve. Se comen durante el Festival de Medio Otoño bajo la luna llena.', en: 'Round pastry cakes with lotus seed paste or salted egg yolk filling, decorated with embossed stamps. Eaten during the Mid-Autumn Festival under the full moon.' },

  // ═══ WORLD ═══
  30002: { es: 'Galletas mantequillosas con ralladura de limón fresco y un glaseado ácido de limón. Crujientes por fuera, suaves por dentro — el equilibrio perfecto entre dulce y cítrico.', en: 'Buttery cookies with fresh lemon zest and a tangy lemon glaze. Crispy outside, soft inside — the perfect balance of sweet and citrus.' },
};

async function updateDescriptions() {
  console.log('📝 DESCRIPCIONES Parte 3: India, Tailandia, Grecia, Japón, México, USA, China, World\n');
  const pool = mysql.createPool({
    host: process.env.DB_HOST, port: parseInt(process.env.DB_PORT) || 4000,
    user: process.env.DB_USER, password: process.env.DB_PASSWORD || process.env.DB_PASS,
    database: process.env.DB_NAME, ssl: { rejectUnauthorized: false }
  });
  const conn = await pool.getConnection();
  let count = 0;
  for (const [id, desc] of Object.entries(descriptions)) {
    await conn.query('UPDATE recipes SET description = ? WHERE id = ?', [JSON.stringify(desc), parseInt(id)]);
    count++;
  }
  console.log(`✅ ${count} descripciones actualizadas`);
  conn.release(); pool.end();
}
updateDescriptions();
