import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const descriptions = {
  // ═══ ITALY ═══
  76: { es: 'La pizza en su forma más pura: masa fina y elástica con salsa de tomate San Marzano, mozzarella di bufala fresca y albahaca. Horneada en horno de leña a 450°C por 90 segundos.', en: 'Pizza in its purest form: thin elastic dough with San Marzano tomato sauce, fresh buffalo mozzarella and basil. Wood-fired at 900°F for 90 seconds.' },
  77: { es: 'Arroz arborio tostado y cocido lentamente con caldo, vino blanco y hongos porcini secos rehidratados. Terminado con mantequilla y parmesano (mantecatura) para una textura sedosa.', en: 'Arborio rice toasted and slowly cooked with broth, white wine and rehydrated dried porcini mushrooms. Finished with butter and parmesan (mantecatura) for a silky texture.' },
  78: { es: 'Capas de bizcochos savoiardi empapados en espresso, alternadas con crema de mascarpone, yemas y claras batidas. Espolvoreado con cacao amargo. El postre italiano sin horno más famoso.', en: 'Layers of espresso-soaked savoiardi biscuits alternated with mascarpone cream, yolks and whipped whites. Dusted with bitter cocoa. Italy\'s most famous no-bake dessert.' },
  79: { es: 'Ñoquis suaves de papa hechos a mano, servidos con pesto genovés fresco de albahaca, piñones, ajo, parmesano y aceite de oliva. Ligereza italiana en cada bocado.', en: 'Soft handmade potato gnocchi served with fresh Genovese basil pesto, pine nuts, garlic, parmesan and olive oil. Italian lightness in every bite.' },
  80: { es: 'Helado italiano artesanal con base de crema pastelera (leche, yemas y azúcar), churneado lentamente para una textura densa y cremosa. Más intenso que el ice cream americano.', en: 'Artisan Italian gelato with a custard base (milk, yolks and sugar), slowly churned for a dense, creamy texture. More intense than American ice cream.' },
  81: { es: 'Tubos de masa crujiente frita rellenos de crema de ricotta dulce con chips de chocolate y pistachos. El postre siciliano que cruje al morderlo.', en: 'Crispy fried dough tubes filled with sweet ricotta cream, chocolate chips and pistachios. The Sicilian dessert that crunches when you bite.' },
  82: { es: 'Pan plano italiano esponjoso y aceitoso, con hoyuelos que atrapan aceite de oliva y sal gruesa, aromatizado con romero fresco. Crujiente por fuera, suave como una nube por dentro.', en: 'Fluffy, oily Italian flatbread with dimples that trap olive oil and coarse salt, fragrant with fresh rosemary. Crispy outside, cloud-soft inside.' },
  83: { es: 'Corte de caña de ternera con hueso y tuétano, estofado lentamente en vino blanco, caldo y gremolata de limón. El tuétano se come con cuchara — eso es Milán.', en: 'Veal shank cross-cut with bone and marrow, slowly braised in white wine, broth and lemon gremolata. The marrow is eaten with a spoon — that\'s Milan.' },
  84: { es: 'Spaghetti con salsa de yemas de huevo, pecorino romano, guanciale crujiente y pimienta negra. Sin crema — la cremosidad viene solo del huevo y el queso. Roma auténtica.', en: 'Spaghetti with egg yolk sauce, pecorino romano, crispy guanciale and black pepper. No cream — the creaminess comes only from egg and cheese. Authentic Rome.' },
  85: { es: 'Bolas de arroz rellenas de ragú y mozzarella, empanizadas y fritas hasta dorar. Crujientes por fuera, con un corazón de queso derretido. Street food siciliano.', en: 'Rice balls stuffed with ragù and mozzarella, breaded and fried until golden. Crispy outside with a molten cheese heart. Sicilian street food.' },
  86: { es: 'Rebanadas de pan rústico tostado frotadas con ajo, cubiertas con tomates frescos picados, albahaca, aceite de oliva virgen extra y sal. La simplicidad toscana perfecta.', en: 'Toasted rustic bread slices rubbed with garlic, topped with fresh diced tomatoes, basil, extra virgin olive oil and salt. Perfect Tuscan simplicity.' },
  87: { es: 'Pasta con solo dos ingredientes de sabor: pecorino romano y pimienta negra recién molida. La grasa del queso y el agua de pasta crean una salsa cremosa. Minimalismo romano.', en: 'Pasta with just two flavor ingredients: pecorino romano and freshly ground black pepper. The cheese fat and pasta water create a creamy sauce. Roman minimalism.' },
  88: { es: 'Masa de pizza plegada sobre sí misma rellena de mozzarella, ricotta, salami y albahaca, sellada y horneada hasta que se infle dorada. La pizza cerrada napolitana.', en: 'Pizza dough folded over itself filled with mozzarella, ricotta, salami and basil, sealed and baked until puffed and golden. The Neapolitan closed pizza.' },
  90: { es: 'Láminas ultrafinas de res cruda de primera calidad, bañadas en aceite de oliva y limón, con escamas de parmesano y rúcula. Elegancia italiana en su forma más minimalista.', en: 'Ultra-thin slices of premium raw beef, drizzled with olive oil and lemon, with parmesan shavings and arugula. Italian elegance at its most minimal.' },
  91: { es: 'Fettuccine bañados en una salsa cremosa de mantequilla y parmesano. Inventado en Roma en 1914 por Alfredo di Lelio — simple, rico e irresistiblemente indulgente.', en: 'Fettuccine bathed in a creamy butter and parmesan sauce. Invented in Rome in 1914 by Alfredo di Lelio — simple, rich and irresistibly indulgent.' },
  92: { es: 'Capas de berenjena frita, salsa de tomate casera y mozzarella gratinada al horno. El plato vegetariano del sur de Italia que rivaliza con cualquier lasaña.', en: 'Layers of fried eggplant, homemade tomato sauce and melted mozzarella baked until bubbly. Southern Italy\'s vegetarian dish that rivals any lasagna.' },
  93: { es: 'Sopa rústica italiana cargada de verduras de temporada, pasta corta, frijoles y caldo de tomate. Cada región y cada abuela tiene su propia versión.', en: 'Rustic Italian soup loaded with seasonal vegetables, short pasta, beans and tomato broth. Every region and every grandmother has their own version.' },
  94: { es: 'Pan dulce alto y esponjoso con frutas confitadas y pasas, fermentado con levadura natural durante horas. El regalo navideño milanés que perfuma toda la casa.', en: 'Tall, fluffy sweet bread with candied fruits and raisins, naturally leavened for hours. The Milanese Christmas gift that fills the whole house with aroma.' },
  95: { es: 'Crema de nata cocida con azúcar y vainilla, cuajada con gelatina hasta obtener una textura temblorosa y sedosa. Se desmolda y baña en coulis de frutos rojos.', en: 'Cream cooked with sugar and vanilla, set with gelatin to a wobbly, silky texture. Unmolded and drizzled with berry coulis.' },
  96: { es: 'Polenta de maíz cocida lentamente hasta quedar cremosa, servida con un ragú de carne lento y parmesano. Comida de montaña del norte de Italia.', en: 'Cornmeal polenta slowly cooked until creamy, served with a slow meat ragù and parmesan. Mountain food from northern Italy.' },
  97: { es: 'Pollo troceado dorado en sartén y cocido en salsa de tomate con aceitunas, alcaparras, vino blanco y romero. El guiso de pollo rústico de la campiña italiana.', en: 'Chicken pieces browned in a pan and braised in tomato sauce with olives, capers, white wine and rosemary. Rustic chicken stew from the Italian countryside.' },
  98: { es: 'Láminas de prosciutto crudo curado envolviendo gajos de melón cantalupo fresco. El antipasto italiano más elegante — dulce y salado en armonía perfecta.', en: 'Slices of cured prosciutto crudo wrapping fresh cantaloupe melon wedges. The most elegant Italian antipasto — sweet and salty in perfect harmony.' },
  189: { es: 'Capas de pasta ancha con ragú boloñés de carne cocido durante horas, bechamel cremosa y parmesano gratinado. El plato dominical de Emilia-Romaña.', en: 'Wide pasta layers with hours-slow-cooked Bolognese meat ragù, creamy béchamel and gratinated parmesan. The Sunday dish of Emilia-Romagna.' },
  193: { es: 'Chuletón de ternera chianina de 4cm de grosor, asado sobre brasas de encina. Sellado por fuera, rojo por dentro, sazonado solo con sal, pimienta y aceite de oliva. Florencia en un plato.', en: 'Chianina beef T-bone steak 4cm thick, grilled over oak embers. Seared outside, red inside, seasoned with just salt, pepper and olive oil. Florence on a plate.' },
  194: { es: 'Pasta fresca rellena de ricotta cremosa, espinacas y nuez moscada, servida con salsa de mantequilla y salvia dorada. La delicadeza de la pasta rellena italiana.', en: 'Fresh pasta filled with creamy ricotta, spinach and nutmeg, served with brown butter and golden sage sauce. The delicacy of Italian filled pasta.' },
  200: { es: 'Una bola de gelato de vainilla "ahogada" en un shot de espresso caliente. El postre-café italiano de dos ingredientes que se prepara en 10 segundos.', en: 'A scoop of vanilla gelato "drowned" in a shot of hot espresso. The two-ingredient Italian dessert-coffee made in 10 seconds.' },
  201: { es: 'Galletas italianas crujientes horneadas dos veces con almendras enteras, perfectas para mojar en Vin Santo. Originarias de Prato, Toscana — duran semanas sin perder crocancia.', en: 'Twice-baked Italian cookies studded with whole almonds, perfect for dipping in Vin Santo. From Prato, Tuscany — they stay crunchy for weeks.' },
  202: { es: 'Rodajas de tomate fresco, mozzarella di bufala y hojas de albahaca, rociadas con aceite de oliva virgen extra y sal. Los colores de la bandera italiana en un plato.', en: 'Fresh tomato slices, buffalo mozzarella and basil leaves, drizzled with extra virgin olive oil and salt. The Italian flag colors on a plate.' },
  203: { es: 'Ensalada toscana de pan duro remojado en vinagre, mezclado con tomates maduros, pepino, cebolla roja, albahaca y aceite de oliva. La forma toscana de no desperdiciar pan.', en: 'Tuscan salad of stale bread soaked in vinegar, tossed with ripe tomatoes, cucumber, red onion, basil and olive oil. The Tuscan way to never waste bread.' },
  205: { es: 'Masa hojaladrada en forma de concha rellena de crema de ricotta con naranja confitada y canela. Pastelería napolitana de capas crujientes y centro cremoso.', en: 'Shell-shaped flaky pastry filled with ricotta cream, candied orange and cinnamon. Neapolitan pastry with crispy layers and a creamy center.' },
  206: { es: 'El plato de pasta más famoso del mundo: spaghetti con ragú boloñés de carne cocido a fuego lento con tomate, zanahoria, apio y vino tinto. Sabor profundo y reconfortante.', en: 'The world\'s most famous pasta dish: spaghetti with slow-simmered Bolognese meat ragù with tomato, carrot, celery and red wine. Deep, comforting flavor.' },
  207: { es: 'Pasta rellena en forma de anillo con carne y parmesano, servida en un caldo de pollo y res cristalino y perfumado. El abrazo italiano en forma de sopa.', en: 'Ring-shaped filled pasta with meat and parmesan, served in a clear, fragrant chicken and beef broth. The Italian hug in soup form.' },
  208: { es: 'Milanesa de ternera empanizada en pan rallado fino, frita en mantequilla clarificada hasta dorar. Crujiente, dorada y jugosa — el orgullo de la cocina milanesa.', en: 'Veal cutlet breaded in fine breadcrumbs, fried in clarified butter until golden. Crispy, golden and juicy — the pride of Milanese cuisine.' },
  209: { es: 'Crema caliente y espumosa de yemas batidas con azúcar y vino Marsala. Postre decadente que se prepara en 5 minutos y se sirve en copas elegantes.', en: 'Warm, foamy cream of yolks beaten with sugar and Marsala wine. Decadent dessert made in 5 minutes and served in elegant glasses.' },
  210: { es: 'Bolitas de masa choux fritas, rellenas de crema pastelera y espolvoreadas con azúcar glass. El dulce napolitano del Día de San José (19 de marzo).', en: 'Fried choux pastry balls filled with pastry cream and dusted with powdered sugar. The Neapolitan sweet for Saint Joseph\'s Day (March 19).' },
  // ═══ SPAIN ═══
  99: { es: 'Arroz cocinado en paellera ancha con pollo, conejo, judía verde, garrofón, azafrán y el preciado socarrat del fondo. El plato que define Valencia y toda España.', en: 'Rice cooked in a wide paella pan with chicken, rabbit, green beans, lima beans, saffron and the prized socarrat from the bottom. The dish that defines Valencia and all of Spain.' },
  100: { es: 'Tortilla gruesa y jugosa de huevos y patatas confitadas en aceite de oliva. Cuajada por fuera, ligeramente cremosa por dentro. La tapa española por excelencia — con o sin cebolla.', en: 'Thick, juicy omelette of eggs and potatoes slow-cooked in olive oil. Set outside, slightly creamy inside. The quintessential Spanish tapa — with or without onion.' },
  101: { es: 'Sopa fría de tomates maduros, pimiento, pepino, ajo, vinagre de Jerez y aceite de oliva, triturada hasta quedar sedosa. Andalucía embotellada — se sirve helada en verano.', en: 'Cold soup of ripe tomatoes, pepper, cucumber, garlic, sherry vinegar and olive oil, blended until silky. Bottled Andalusia — served ice-cold in summer.' },
  102: { es: 'Pulpo cocido y cortado en rodajas gruesas, servido sobre papas cocidas con pimentón de la Vera, sal gruesa y aceite de oliva virgen extra. Galicia en un plato de madera.', en: 'Boiled octopus sliced thick, served over boiled potatoes with pimentón de la Vera, coarse salt and extra virgin olive oil. Galicia on a wooden plate.' },
  103: { es: 'Cubos de papa frita crujientes bañados en salsa brava picante (tomate con pimentón y cayena) y alioli. La tapa madrileña que nunca falta en el bar.', en: 'Crispy fried potato cubes bathed in spicy brava sauce (tomato with paprika and cayenne) and alioli. The Madrid tapa that never misses at the bar.' },
  104: { es: 'Cilindros cremosos de bechamel densa con trocitos de jamón serrano, empanizados y fritos hasta quedar dorados. Al morderlos, el interior fluye cremoso. La tapa perfecta.', en: 'Creamy cylinders of thick béchamel with serrano ham bits, breaded and fried until golden. When bitten, the inside flows creamy. The perfect tapa.' },
  105: { es: 'Gambas enteras salteadas en abundante aceite de oliva con láminas de ajo dorado y guindilla picante. Se sirven chisporroteando en cazuela de barro con pan para mojar.', en: 'Whole prawns sautéed in plenty of olive oil with golden garlic slices and hot chili pepper. Served sizzling in a clay dish with bread for dipping.' },
  106: { es: 'Guiso asturiano de judiones blancos gigantes con chorizo, morcilla, lacón y panceta, cocido lentamente hasta que los frijoles absorben todo el sabor del cerdo.', en: 'Asturian stew of giant white beans with chorizo, blood sausage, ham hock and pancetta, slow-cooked until the beans absorb all the pork flavor.' },
  108: { es: 'Crema de yemas con leche, azúcar, canela y ralladura de limón, cuajada y cubierta con una capa de azúcar caramelizado con hierro candente. La prima catalana del crème brûlée.', en: 'Custard of yolks with milk, sugar, cinnamon and lemon zest, set and topped with a layer of sugar caramelized with a hot iron. The Catalan cousin of crème brûlée.' },
  109: { es: 'Masa de agua y harina extruida en forma de estrella y frita hasta dorar, rebozada en azúcar con canela. Se mojan en chocolate espeso y caliente. Desayuno y merienda española.', en: 'Water and flour dough piped in star shapes and fried until golden, coated in cinnamon sugar. Dipped in thick hot chocolate. Spanish breakfast and afternoon snack.' },
  110: { es: 'Tarta densa de almendras molidas sin harina de trigo, perfumada con limón y canela. Decorada con la Cruz de Santiago en azúcar glass. Postre medieval gallego.', en: 'Dense ground almond cake without wheat flour, fragrant with lemon and cinnamon. Decorated with the Cross of Santiago in powdered sugar. Medieval Galician dessert.' },
  111: { es: 'Guiso madrileño de garbanzos con múltiples carnes (pollo, ternera, tocino, chorizo, morcilla), verduras y fideos. Se sirve en tres vuelcos: sopa, verduras y carnes.', en: 'Madrid stew of chickpeas with multiple meats (chicken, beef, bacon, chorizo, blood sausage), vegetables and noodles. Served in three courses: broth, vegetables and meats.' },
  112: { es: 'Lechón entero asado lentamente en horno de leña hasta que la piel queda crujiente como cristal y la carne tierna. Se parte con un plato — tradición segoviana.', en: 'Whole suckling pig slowly roasted in a wood oven until the skin is glass-crispy and the meat tender. Carved with a plate — Segovian tradition.' },
  113: { es: 'Lomo de bacalao confitado a baja temperatura en aceite de oliva, que al agitar la cazuela suelta su gelatina y crea una salsa emulsionada brillante. Técnica vasca ancestral.', en: 'Cod loin slowly poached in olive oil, which when the pan is swirled releases its gelatin and creates a shiny emulsified sauce. Ancient Basque technique.' },
  114: { es: 'Verduras mediterráneas (berenjena, pimiento, cebolla, tomate) asadas enteras al horno o brasas, peladas y aliñadas con aceite de oliva y ajo. Sencillez catalana pura.', en: 'Mediterranean vegetables (eggplant, pepper, onion, tomato) roasted whole in the oven or over coals, peeled and dressed with olive oil and garlic. Pure Catalan simplicity.' },
  115: { es: 'Pimientos verdes pequeños de Padrón fritos en aceite de oliva caliente y espolvoreados con sal gruesa. Unos pican, otros no — la ruleta rusa gallega más deliciosa.', en: 'Small green Padrón peppers fried in hot olive oil and sprinkled with coarse salt. Some are spicy, some are not — the most delicious Galician Russian roulette.' },
  116: { es: 'Arroz teñido de negro intenso con tinta de calamar, cocido con calamares, gambas, ajo y caldo de pescado. Dramático en apariencia, profundo en sabor a mar.', en: 'Rice dyed jet black with squid ink, cooked with squid, prawns, garlic and fish stock. Dramatic in appearance, deep in ocean flavor.' },
  117: { es: 'Anillos de calamar rebozados en harina y fritos en aceite de oliva caliente hasta quedar crujientes y dorados. Servidos con limón — la tapa de bar español más universal.', en: 'Squid rings dredged in flour and fried in hot olive oil until crispy and golden. Served with lemon — the most universal Spanish bar tapa.' },
  118: { es: 'Crema fría de tomate, pan duro, ajo, aceite de oliva y vinagre de Jerez, más espesa que el gazpacho. Coronada con jamón ibérico y huevo duro. Joya cordobesa.', en: 'Cold cream of tomato, stale bread, garlic, olive oil and sherry vinegar, thicker than gazpacho. Crowned with Iberian ham and hard-boiled egg. Córdoba\'s jewel.' },
  254: { es: 'Croquetas de bechamel ultracremosa con cubitos de jamón ibérico de bellota, doble empanizado y fritas hasta la perfección. El interior debe fluir al morderlas. Premium español.', en: 'Ultra-creamy béchamel croquettes with acorn-fed Iberian ham cubes, double-breaded and fried to perfection. The inside must flow when bitten. Spanish premium.' },
  256: { es: 'Pierna o paletilla de cordero asada lentamente con ajo, romero y vino blanco hasta que la carne se cae del hueso. Aroma que llena la casa — la mesa dominical castellana.', en: 'Leg or shoulder of lamb slowly roasted with garlic, rosemary and white wine until the meat falls off the bone. House-filling aroma — the Castilian Sunday table.' },
  258: { es: 'Boquerones, chanquetes y calamares enharinados y fritos en aceite de oliva muy caliente, servidos en cucurucho de papel con limón. El chiringuito malagueño en su máxima expresión.', en: 'Anchovies, whitebait and squid floured and fried in very hot olive oil, served in a paper cone with lemon. The Málaga beach bar at its finest.' },
  // ═══ FRANCE ═══
  119: { es: 'Guiso provenzal de verduras mediterráneas (berenjena, calabacín, pimiento, tomate) cocidas lentamente en aceite de oliva con hierbas de Provenza. La huerta francesa en un plato.', en: 'Provençal stew of Mediterranean vegetables (eggplant, zucchini, bell pepper, tomato) slowly cooked in olive oil with herbes de Provence. The French garden on a plate.' },
  120: { es: 'Tarta salada de masa quebrada rellena de una mezcla cremosa de huevos, crema, queso gruyère y lardones de tocino ahumado. Lorraine compartida en cada brunch.', en: 'Savory shortcrust tart filled with a creamy mix of eggs, cream, gruyère cheese and smoked bacon lardons. Lorraine shared at every brunch.' },
  121: { es: 'Pollo troceado cocido lentamente en vino tinto de Borgoña con champiñones, cebollitas perla, tocino y un bouquet garni. El guiso campestre francés por excelencia.', en: 'Chicken pieces slowly braised in Burgundy red wine with mushrooms, pearl onions, bacon and a bouquet garni. The quintessential French country stew.' },
  123: { es: 'Estofado de res cocido durante horas en vino tinto de Borgoña con zanahorias, cebollitas perla y champiñones. La carne se deshace con el tenedor — alta cocina de origen campesino.', en: 'Beef stew braised for hours in Burgundy red wine with carrots, pearl onions and mushrooms. Fork-tender meat — haute cuisine with peasant origins.' },
  124: { es: 'Sopa de pescadores marsellesa con múltiples pescados y mariscos cocidos en caldo de tomate azafranado, servida con rouille (mayonesa de ajo y azafrán) y crutones. El mar Mediterráneo en un bol.', en: 'Marseille fisherman\'s soup with multiple fish and shellfish cooked in saffron tomato broth, served with rouille (garlic-saffron mayo) and croutons. The Mediterranean sea in a bowl.' },
  125: { es: 'Muslo de pato curado en sal y especias, cocido lentamente en su propia grasa hasta quedar ultra tierno. La piel se crispa al final. Preservación francesa convertida en lujo.', en: 'Duck leg cured in salt and spices, slowly cooked in its own fat until ultra-tender. The skin is crisped at the end. French preservation turned into luxury.' },
  126: { es: 'Masa laminada con mantequilla francesa doblada en 27 capas, fermentada y horneada hasta explotar en capas doradas y mantequillosas. La cumbre de la panadería francesa.', en: 'Dough laminated with French butter folded into 27 layers, proofed and baked until bursting into golden, buttery layers. The pinnacle of French baking.' },
  127: { es: 'Galletas de merengue de almendras con superficie lisa y "pies" rugosos, unidas con ganache de chocolate o buttercream. Colores vibrantes y textura crujiente-chiclosa.', en: 'Almond meringue cookies with smooth tops and ruffled "feet," sandwiched with chocolate ganache or buttercream. Vibrant colors and crispy-chewy texture.' },
  128: { es: 'Chocolate negro derretido y combinado con claras batidas a punto de nieve, sin harina ni crema. Textura aireada, intensa y aterciopelada — el postre francés de 3 ingredientes.', en: 'Dark chocolate melted and folded with stiffly beaten egg whites, no flour or cream. Airy, intense and velvety texture — the 3-ingredient French dessert.' },
  129: { es: 'Crema de vainilla horneada a baja temperatura hasta cuajar, cubierta con una capa de azúcar caramelizado al soplete. Al romper la costra suena un crack satisfactorio.', en: 'Vanilla custard baked at low temperature until set, topped with a torched caramelized sugar layer. Breaking the crust makes a satisfying crack.' },
  130: { es: 'Guiso rústico de Languedoc con judiones blancos, salchicha de Toulouse, confit de pato y pan rallado gratinado. Se cocina lento y se gratina varias veces. Comida de invierno francesa.', en: 'Rustic Languedoc stew with white beans, Toulouse sausage, duck confit and gratinated breadcrumbs. Slow-cooked and gratinated multiple times. French winter food.' },
  131: { es: 'Filete grueso de carne de res sellado en sartén de hierro con mantequilla y tomillo, acompañado de papas fritas dobles (blanqueadas y fritas). La brasserie parisina clásica.', en: 'Thick beef steak seared in a cast iron skillet with butter and thyme, served with double-fried frites (blanched then fried). The classic Parisian brasserie.' },
  132: { es: 'Vieiras doradas en mantequilla con costra caramelizada, servidas en su concha con salsa de vino blanco, crema y gruyère gratinado. Elegancia de la costa bretona.', en: 'Scallops seared in butter with a caramelized crust, served in their shell with white wine, cream and gratinated gruyère sauce. Breton coastal elegance.' },
  133: { es: 'Sándwich de pan de molde con jamón y queso gruyère, cubierto con bechamel y gratinado al horno. El croque monsieur: el sándwich caliente más indulgente de Francia.', en: 'Sandwich of sliced bread with ham and gruyère cheese, topped with béchamel and oven-gratinated. The croque monsieur: France\'s most indulgent hot sandwich.' },
  134: { es: 'Tarta invertida de manzanas caramelizadas en mantequilla y azúcar, cubierta con masa que al voltear queda abajo. Creada por accidente en el Hotel Tatin — error delicioso.', en: 'Upside-down tart of apples caramelized in butter and sugar, covered with pastry that ends up on the bottom when flipped. Created by accident at Hotel Tatin — delicious mistake.' },
  135: { es: 'Bolitas de masa choux hueca horneada, rellenas de helado de vainilla y bañadas en ganache de chocolate caliente. Contraste de temperaturas y texturas en cada bocado.', en: 'Hollow baked choux pastry puffs filled with vanilla ice cream and drizzled with hot chocolate ganache. Temperature and texture contrast in every bite.' },
  136: { es: 'Crêpes finas flameadas en salsa de mantequilla, azúcar, jugo de naranja y Grand Marnier encendido en la mesa. El espectáculo dulce de la cocina francesa.', en: 'Thin crêpes flambéed in a sauce of butter, sugar, orange juice and Grand Marnier lit at the table. The sweet spectacle of French cuisine.' },
  137: { es: 'Caracoles de Borgoña al horno en sus conchas, rellenos de mantequilla de ajo, perejil y chalota. Se extraen con pinza y tenedor especial — ritual gastronómico francés.', en: 'Burgundy snails baked in their shells, filled with garlic, parsley and shallot butter. Extracted with special tongs and fork — French gastronomic ritual.' },
  261: { es: 'Cebolla caramelizada largo rato en mantequilla, con caldo de res, vino blanco y gratinada con pan crujiente y queso gruyère derretido. La sopa que calienta el alma de París.', en: 'Onion caramelized slowly in butter, with beef broth, white wine and gratinated with crusty bread and melted gruyère cheese. The soup that warms the soul of Paris.' },
  263: { es: 'Ensalada de Niza con atún, huevo duro, judías verdes, aceitunas niçoise, anchoas, tomate y papa, aliñada con vinagreta de aceite de oliva. La Côte d\'Azur en un plato.', en: 'Nice salad with tuna, hard-boiled egg, green beans, niçoise olives, anchovies, tomato and potato, dressed with olive oil vinaigrette. The Côte d\'Azur on a plate.' },
  264: { es: 'Suflé esponjoso y aireado de queso gruyère que sube dramáticamente en el horno. Dorado por fuera, cremoso y tembloroso por dentro. Debe servirse inmediatamente.', en: 'Fluffy, airy gruyère cheese soufflé that rises dramatically in the oven. Golden outside, creamy and wobbly inside. Must be served immediately.' },
  265: { es: 'Coca plana de masa de pan cubierta con cebolla caramelizada lentamente, anchoas y aceitunas negras de Niza. La "pizza" provenzal del sur de Francia.', en: 'Flat bread dough topped with slowly caramelized onion, anchovies and Nice black olives. The Provençal "pizza" of southern France.' },
  269: { es: 'Suflé de chocolate negro que sube ligero y aireado en el horno, con exterior firme y corazón fundido e intenso. Se desinfla en minutos — hay que comerlo al instante.', en: 'Dark chocolate soufflé that rises light and airy in the oven, with a firm exterior and intense molten heart. Deflates in minutes — must be eaten instantly.' },
};

async function updateDescriptions() {
  console.log('📝 DESCRIPCIONES Parte 2: Italia, España, Francia\n');
  const pool = mysql.createPool({
    host: process.env.DB_HOST, port: parseInt(process.env.DB_PORT) || 4000,
    user: process.env.DB_USER, password: process.env.DB_PASSWORD || process.env.DB_PASS,
    database: process.env.DB_NAME, ssl: { rejectUnauthorized: false }
  });
  const conn = await pool.getConnection();
  let count = 0;
  for (const [id, desc] of Object.entries(descriptions)) {
    await conn.query('UPDATE recipes SET description = ? WHERE id = ?', [JSON.stringify(desc), parseInt(id)]);
    count++;
  }
  console.log(`✅ ${count} descripciones actualizadas`);
  conn.release(); pool.end();
}
updateDescriptions();
