import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const descriptionsMap = [
  // CHINA
  { match: 'kung_pao', es: 'Trozos de pollo crujientes salteados al wok con chiles secos, cacahuates tostados y la clásica salsa agridulce-picante de Sichuan. Un plato explosivo con el adictivo sabor del málà.', en: 'Crispy chicken pieces wok-tossed with dried chiles, toasted peanuts and the classic sweet-sour-spicy Sichuan sauce. An explosive dish with the addictive málà flavor.' },
  { match: 'mapo_tofu', es: 'Cubos de tofu sedoso nadando en una salsa roja y ardiente de doubanjiang, carne de cerdo picada y pimienta de Sichuan que adormece la lengua. Comida reconfortante picante de Chengdu.', en: 'Silky tofu cubes swimming in a fiery red doubanjiang sauce with minced pork and tongue-numbing Sichuan peppercorn. Spicy comfort food from Chengdu.' },
  { match: 'peking_duck', es: 'Pato entero lacado con miel y especias, asado hasta obtener una piel ultra crujiente y carne tierna. Se trincha en la mesa y se sirve en crepas finas con cebollín y salsa hoisin.', en: 'Whole duck glazed with honey and spices, roasted until the skin is ultra-crispy and the meat is tender. Carved tableside and served in thin crepes with scallion and hoisin sauce.' },
  { match: 'jiaozi', es: 'Empanadillas chinas rellenas de verduras y cerdo, envueltas a mano con masa delgada. Se pueden hervir, freír o cocer al vapor — el dumpling perfecto para compartir.', en: 'Chinese dumplings filled with vegetables and pork, hand-wrapped in thin dough. Boiled, pan-fried or steamed — the perfect dumpling to share.' },
  { match: 'sweet_sour_pork', es: 'Trozos de cerdo rebozados y fritos hasta quedar crujientes, bañados en una salsa agridulce vibrante con piña, pimiento y cebolla. El clásico cantonés que todos aman.', en: 'Battered and fried pork pieces coated in a vibrant sweet and sour sauce with pineapple, bell pepper and onion. The Cantonese classic everyone loves.' },
  { match: 'lo_mein', es: 'Fideos de trigo salteados al wok con vegetales crujientes, proteína y una salsa oscura de soya y aceite de sésamo. Street food chino en su máxima expresión.', en: 'Wheat noodles wok-tossed with crispy vegetables, protein and a dark soy and sesame oil sauce. Chinese street food at its finest.' },
  { match: 'yangzhou', es: 'Arroz salteado al wok a fuego alto con huevo, camarones, jamón chino (char siu), chícharos y cebollín. El arroz frito original de la ciudad de Yangzhou.', en: 'Rice wok-fried over high heat with egg, shrimp, Chinese ham (char siu), peas and scallions. The original fried rice from the city of Yangzhou.' },
  { match: 'siu_mai', es: 'Pequeñas cestas abiertas de masa wonton rellenas de cerdo y camarón, coronadas con una gamba. Cocidas al vapor en vaporera de bambú — el rey del dim sum cantonés.', en: 'Small open wonton baskets filled with pork and shrimp, topped with a prawn. Steamed in a bamboo steamer — the king of Cantonese dim sum.' },
  { match: 'yu_xiang', es: 'Berenjenas fritas y salteadas en la salsa Yu Xiang de Sichuan: una mezcla adictiva de pasta de chile, vinagre, soya y azúcar con cerdo picado. Sabor agridulce-picante irresistible.', en: 'Fried eggplants stir-fried in Sichuan Yu Xiang sauce: an addictive blend of chili paste, vinegar, soy and sugar with minced pork. Irresistible sweet-sour-spicy flavor.' },
  { match: 'dim_sum', es: 'Selección de bocados al vapor en vaporeras de bambú: har gow de camarón, siu mai de cerdo y dumplings de verduras. Una experiencia compartida de la tradición cantonesa.', en: 'Selection of steamed bites in bamboo baskets: shrimp har gow, pork siu mai and vegetable dumplings. A shared experience from Cantonese tradition.' },
  { match: 'spring_rolls', es: 'Rollitos rellenos de col, zanahoria y champiñones en juliana fina, envueltos en masa crujiente y fritos hasta quedar dorados y crocantes. Se sirven con salsa agridulce.', en: 'Rolls filled with finely julienned cabbage, carrot and mushrooms, wrapped in crispy dough and fried until golden and crunchy. Served with sweet and sour sauce.' },
  { match: 'sweet_spring_rolls', es: 'Rollitos de masa crujiente rellenos de plátano maduro con canela y azúcar morena. Fritos y espolvoreados con azúcar glass — el postre callejero asiático más adictivo.', en: 'Crispy dough rolls filled with ripe banana, cinnamon and brown sugar. Fried and dusted with powdered sugar — the most addictive Asian street dessert.' },
  { match: 'wonton_soup', es: 'Caldo cristalino de pollo con dumplings de masa fina rellenos de cerdo y camarones picados con jengibre. Los wontons flotan como nubes — sopa reconfortante cantonesa.', en: 'Clear chicken broth with thin-wrapper dumplings filled with minced pork and shrimp with ginger. Wontons float like clouds — comforting Cantonese soup.' },
  { match: 'mooncakes', es: 'Pasteles redondos de masa con relleno de pasta de loto dulce y yema de huevo de pato salada en el centro. Se comen durante el Festival del Medio Otoño chino.', en: 'Round pastries with sweet lotus paste filling and a salted duck egg yolk in the center. Eaten during the Chinese Mid-Autumn Festival.' },
  
  // JAPAN
  { match: 'ramen_tonkotsu', es: 'Caldo de huesos de cerdo hervido durante horas hasta obtener un broth cremoso y lechoso. Servido con fideos ramen, chashu de cerdo, huevo marinado y nori.', en: 'Pork bone broth simmered for hours until creamy and milky. Served with ramen noodles, pork chashu, marinated egg and nori.' },
  { match: 'sushi_roll', es: 'Rollos de sushi con arroz sazonado con vinagre, alga nori y rellenos frescos como salmón, aguacate y pepino. El arte japonés de la perfección en cada bocado.', en: 'Sushi rolls with vinegared rice, nori seaweed and fresh fillings like salmon, avocado and cucumber. The Japanese art of perfection in every bite.' },
  { match: 'okonomiyaki', es: 'Tortilla espesa de masa con col rallada, panceta de cerdo, salsa okonomiyaki, mayonesa japonesa, bonito danzante y alga aonori. El "pancake salado" de Osaka.', en: 'Thick batter pancake loaded with shredded cabbage, pork belly, okonomiyaki sauce, Japanese mayo, dancing bonito and aonori seaweed. Osaka\'s famous savory pancake.' },
  { match: 'japan_gyoza', es: 'Empanadillas japonesas con masa fina rellenas de cerdo y col, doradas a la plancha por un lado y cocidas al vapor. Crujientes y jugosas, servidas con salsa de soya y vinagre.', en: 'Japanese thin-wrapper dumplings filled with pork and cabbage, pan-fried on one side and steamed. Crispy and juicy, served with soy sauce and vinegar.' },
  { match: 'katsudon', es: 'Bol de arroz cubierto con tonkatsu — chuleta de cerdo empanizada y frita — bañada en salsa de huevo semicuajado. Comida reconfortante japonesa por excelencia.', en: 'Rice bowl topped with tonkatsu — breaded and fried pork cutlet — bathed in a semi-set egg sauce. The ultimate Japanese comfort food.' },
  { match: 'takoyaki', es: 'Bolitas crujientes de masa rellenas de pulpo tierno, cubiertas con salsa takoyaki, mayonesa, bonito y aonori. El snack callejero icónico de Osaka.', en: 'Crispy batter balls filled with tender octopus, topped with takoyaki sauce, mayo, bonito flakes and aonori. Osaka\'s iconic street snack.' },
  { match: 'yakitori', es: 'Brochetas de pollo asadas sobre carbón binchotan, bañadas en tare dulce de soya o simplemente con sal. El izakaya japonés en su forma más pura.', en: 'Chicken skewers grilled over binchotan charcoal, basted with sweet soy tare or simply with salt. The Japanese izakaya at its purest.' },
  { match: 'onigiri', es: 'Bolas de arroz al vinagre moldeadas a mano, rellenas de salmón, ciruela encurtida o atún con mayonesa, envueltas en alga nori crujiente. El snack portátil de Japón.', en: 'Hand-molded vinegared rice balls, filled with salmon, pickled plum or tuna mayo, wrapped in crispy nori seaweed. Japan\'s portable snack.' },
  { match: 'omurice', es: 'Arroz frito con ketchup envuelto en una tortilla de huevo cremosa y sedosa. Se abre en la mesa para cubrir el arroz. Comfort food japonés con influencia occidental.', en: 'Ketchup fried rice wrapped in a creamy, silky egg omelette. Split open at the table to cover the rice. Japanese comfort food with Western influence.' },
  { match: 'japan_tempura', es: 'Vegetales y mariscos rebozados en una masa ligera y helada, fritos en aceite caliente hasta quedar crujientes y aireados. Se sirve con tentsuyu y daikon rallado.', en: 'Vegetables and seafood dipped in a light, ice-cold batter, fried in hot oil until crispy and airy. Served with tentsuyu and grated daikon.' },
  { match: 'sashimi', es: 'Láminas ultrafinas de salmón y atún crudos de grado sashimi, servidas sobre hielo con daikon rallado, shiso y wasabi fresco. Frescura japonesa en su máxima expresión.', en: 'Ultra-thin slices of raw sashimi-grade salmon and tuna, served over ice with shredded daikon, shiso and fresh wasabi. Japanese freshness at its peak.' },
  { match: 'katsu_curry', es: 'Curry japonés espeso y dulce con trozos de papa y zanahoria, servido con arroz blanco y una chuleta de cerdo crujiente (tonkatsu) encima. Comfort food de todo Japón.', en: 'Thick, sweet Japanese curry with chunks of potato and carrot, served with white rice and a crispy pork cutlet (tonkatsu) on top. Comfort food across Japan.' },
  { match: 'shabu_shabu', es: 'Láminas finísimas de carne cocinadas al momento (haciendo "shabu shabu") en un caldo hirviendo, servidas con salsas ponzu y sésamo. Diversión en la mesa.', en: 'Paper-thin slices of meat cooked momentarily (making "shabu shabu" sound) in boiling broth, served with ponzu and sesame sauces. Table-side fun.' },
  { match: 'sukiyaki', es: 'Carne de res, tofu, vegetales y fideos cocidos en un caldo poco profundo y dulce de soya, mirin y azúcar. Se sumergen en huevo crudo batido antes de comer.', en: 'Beef, tofu, vegetables and noodles simmered in a shallow sweet soy, mirin and sugar broth. Dipped in beaten raw egg before eating.' },
  { match: 'unagi_don', es: 'Anguila de agua dulce fileteada, glaseada con tare de soya dulce y asada a la parrilla sobre carbón. Servida sobre arroz caliente con sansho. Delicadeza japonesa de verano.', en: 'Freshwater eel filleted, glazed with sweet soy tare and charcoal-grilled. Served over hot rice with sansho pepper. A Japanese summer delicacy.' },
  { match: 'yakisoba', es: 'Fideos de trigo salteados a la plancha con cerdo, col y zanahoria, bañados en salsa yakisoba dulce y espesa. Coronados con jengibre encurtido y aonori.', en: 'Wheat noodles stir-fried on a griddle with pork, cabbage and carrot, tossed in thick sweet yakisoba sauce. Topped with pickled ginger and aonori.' },
  { match: 'karaage', es: 'Trozos de muslo de pollo marinados en soya, sake y jengibre, rebozados en fécula de papa y doble-fritos al estilo japonés. Extra crujientes con mayonesa Kewpie.', en: 'Chicken thigh pieces marinated in soy, sake and ginger, coated in potato starch and double-fried Japanese style. Extra crispy with Kewpie mayo.' },
  { match: 'mochi', es: 'Bolitas de mochi elástico hechas con harina de arroz glutinoso y polvo de matcha, rellenas de pasta dulce de frijol rojo (anko). Postre japonés verde y elegante.', en: 'Chewy mochi balls made with glutinous rice flour and matcha powder, filled with sweet red bean paste (anko). An elegant green Japanese dessert.' },
  { match: 'dorayaki', es: 'Dos esponjosos pancakes japoneses rellenos de anko (pasta de frijol rojo dulce). El snack favorito del gato cósmico Doraemon — dulce, suave y reconfortante.', en: 'Two fluffy Japanese pancakes filled with anko (sweet red bean paste). The favorite snack of cosmic cat Doraemon — sweet, soft and comforting.' },
  { match: 'japan_udon', es: 'Fideos gruesos y elásticos de trigo en un caldo dashi caliente con soya y mirin, coronados con cebollín, kamaboko y tempura de camarón. Reconfortante en invierno.', en: 'Thick and chewy wheat noodles in a hot dashi broth with soy and mirin, topped with scallions, kamaboko and shrimp tempura. Comforting in winter.' },
  { match: 'miso_soup', es: 'Caldo claro de dashi con tofu sedoso, wakame y pasta de miso disuelta. La sopa que acompaña cada comida japonesa — umami en su forma más simple.', en: 'Clear dashi broth with silky tofu, wakame and dissolved miso paste. The soup that accompanies every Japanese meal — umami in its simplest form.' },
  { match: 'tamagoyaki', es: 'Tortilla japonesa enrollada en múltiples capas finas, ligeramente dulce con dashi y mirin. Suave y esponjosa — presente en cada bento box y como sushi de huevo.', en: 'Japanese rolled omelette in multiple thin layers, slightly sweet with dashi and mirin. Soft and fluffy — found in every bento box and as egg sushi.' },
  { match: 'chawanmushi', es: 'Flan salado japonés cocido al vapor con caldo dashi, huevo y pequeños trozos de pollo, camarón y seta shiitake. Textura sedosa y temblorosa — elegancia en una taza.', en: 'Savory Japanese egg custard steamed with dashi broth, chicken, shrimp and shiitake mushroom pieces. Silky and trembling texture — elegance in a cup.' },
  
  // THAILAND
  { match: 'pad_thai', es: 'Fideos de arroz salteados al wok con salsa de tamarindo dulce y ácida, huevo, cacahuates, brotes de soya y camarones. El plato tailandés más famoso del mundo.', en: 'Rice noodles wok-tossed with sweet and sour tamarind sauce, egg, peanuts, bean sprouts and shrimp. The most famous Thai dish in the world.' },
  { match: 'green_curry', es: 'Curry de pasta verde picante con leche de coco, chiles verdes, bambú y hojas de albahaca tailandesa. Aromático, herbal y con un nivel de picante que despierta los sentidos.', en: 'Spicy green curry paste with coconut milk, green chiles, bamboo and Thai basil leaves. Aromatic, herbal and with a heat level that awakens the senses.' },
  { match: 'mango_sticky_rice', es: 'Arroz glutinoso cocido al vapor e impregnado en leche de coco dulce, servido con rodajas de mango maduro fresco. El postre tailandés perfecto.', en: 'Sticky rice steamed and infused in sweet coconut milk, served with slices of fresh ripe mango. The perfect Thai dessert.' },
  { match: 'som_tum', es: 'Ensalada de papaya verde rallada machacada en mortero con chiles, ajo, tomate, cacahuates, jugo de lima y salsa de pescado. Fresca, ácida y ultra picante.', en: 'Green papaya salad pounded in a mortar with chiles, garlic, tomato, peanuts, lime juice and fish sauce. Fresh, sour and ultra spicy.' },
  { match: 'massaman_curry', es: 'Curry rico y suave de influencia musulmana con leche de coco, carne de res, papas, cacahuates tostados y especias cálidas como canela y cardamomo.', en: 'Rich and mild Muslim-influenced curry with coconut milk, beef, potatoes, roasted peanuts and warm spices like cinnamon and cardamom.' },
  { match: 'satay_gai', es: 'Brochetas de pollo marinadas en especias amarillas, asadas a la parrilla y servidas con una espesa y adictiva salsa de cacahuate tailandesa.', en: 'Chicken skewers marinated in yellow spices, grilled and served with a thick, addictive Thai peanut sauce.' },
  { match: 'pad_kra_pao', es: 'Cerdo picado salteado al wok a fuego alto con chiles picantes y hojas de albahaca santa tailandesa (kra pao). Se sirve sobre arroz blanco con un huevo frito de yema líquida.', en: 'Minced pork wok-fried over high heat with spicy chiles and Thai holy basil leaves (kra pao). Served over white rice with a runny fried egg.' },
  { match: 'khao_pad', es: 'Arroz frito tailandés al wok con huevo, ajo, cebolla y salsa de soya ligera, acompañado de rodajas de pepino y limón. Simple, sabroso y sin pretensiones.', en: 'Thai fried rice wok-tossed with egg, garlic, onion and light soy sauce, accompanied by cucumber slices and lime. Simple, tasty and unpretentious.' },
  { match: 'tom_kha_gai', es: 'Sopa cremosa de leche de coco con pollo, perfumada intensamente con raíz de galanga, hierba limón y hojas de lima kaffir. Equilibrio perfecto de dulce, ácido y salado.', en: 'Creamy coconut milk soup with chicken, intensely fragranced with galangal root, lemongrass and kaffir lime leaves. Perfect balance of sweet, sour and salty.' },
  { match: 'khao_soi', es: 'Sopa de fideos de huevo de Chiang Mai con un caldo rico de curry de coco, coronada con fideos fritos crujientes, chalotas, lima y mostaza encurtida.', en: 'Chiang Mai egg noodle soup with a rich coconut curry broth, topped with crispy fried noodles, shallots, lime and pickled mustard greens.' },
  { match: 'pad_see_ew', es: 'Fideos de arroz anchos y masticables salteados al wok con salsa de soya oscura, huevo y brócoli chino. Sabor ahumado intenso por el calor del wok.', en: 'Chewy, wide rice noodles wok-tossed with dark soy sauce, egg and Chinese broccoli. Intense smoky flavor from wok hei.' },
  { match: 'larb_moo', es: 'Ensalada picante tailandesa de carne de cerdo picada cocida, mezclada con jugo de limón, salsa de pescado, chiles secos, menta y arroz tostado triturado.', en: 'Spicy Thai salad of cooked minced pork, mixed with lime juice, fish sauce, dried chiles, mint and toasted crushed rice.' },
  { match: 'pla_goong', es: 'Ensalada tailandesa de camarones con hierba limón fresca picada, chalotas, menta, chile y jugo de limón. Ácida, picante y fragante — frescura marina.', en: 'Thai shrimp salad with fresh chopped lemongrass, shallots, mint, chile and lime juice. Sour, spicy and fragrant — marine freshness.' },
  { match: 'gai_med_ma_moung', es: 'Pollo salteado al wok con anacardos tostados, chiles secos, cebolla y una salsa dulce de soya y ostra. Menos picante, más crujiente.', en: 'Chicken wok-tossed with roasted cashews, dried chiles, onion and a sweet soy and oyster sauce. Less spicy, more crunchy.' },
  { match: 'tom_yum_goong', es: 'Sopa caliente y ácida con camarones enteros, galanga, hierba limón, hojas de lima kaffir y chiles aplastados. El sabor icónico y explosivo de Tailandia en un bol.', en: 'Hot and sour soup with whole shrimp, galangal, lemongrass, kaffir lime leaves and crushed chiles. Thailand\'s iconic and explosive flavor in a bowl.' },
  { match: 'panang_curry', es: 'Curry tailandés espeso y cremoso con pasta de panang, leche de coco espesa, carne tierna y un toque de hojas de lima kaffir finamente rebanadas.', en: 'Thick and creamy Thai curry with panang paste, rich coconut milk, tender meat and a touch of finely sliced kaffir lime leaves.' },
  { match: 'tod_mun_pla', es: 'Pasteles de pescado tailandeses moldeados a mano con pasta de curry rojo, ejotes picados y hojas de lima kaffir, fritos hasta dorar. Elásticos y aromáticos.', en: 'Hand-molded Thai fish cakes with red curry paste, chopped green beans and kaffir lime leaves, fried until golden. Bouncy and aromatic.' },
  { match: 'yam_nua', es: 'Ensalada tailandesa de carne de res a la parrilla cortada fina, con menta, cilantro, cebolla, chile, limón y arroz tostado. Fresca, picante y llena de textura.', en: 'Thai grilled beef salad sliced thinly, with mint, cilantro, onion, chile, lime and toasted rice. Fresh, spicy and full of texture.' },
  
  // INDIA
  { match: 'butter_chicken', es: 'Trozos de pollo tandoori en una rica y suave salsa cremosa de tomate, mantequilla y especias (Murgh Makhani). El curry indio más amado globalmente.', en: 'Tandoori chicken pieces in a rich, smooth and creamy tomato, butter and spice sauce (Murgh Makhani). The most globally loved Indian curry.' },
  { match: 'chicken_tikka_masala', es: 'Trozos de pollo marinados en yogur y especias, asados y servidos en una salsa masala de tomate ligeramente picante. El rey de los restaurantes indios.', en: 'Chicken pieces marinated in yogurt and spices, roasted and served in a mildly spicy tomato masala sauce. The king of Indian restaurants.' },
  { match: 'lamb_biryani', es: 'Arroz basmati perfumado con azafrán y especias enteras, cocinado en capas con carne de cordero marinada. Un festín real en una sola olla.', en: 'Basmati rice fragranced with saffron and whole spices, cooked in layers with marinated lamb. A royal feast in a single pot.' },
  { match: 'palak_paneer', es: 'Cubos de paneer (queso fresco indio) flotando en una salsa espesa de espinacas puré, sazonada con ajo, jengibre y garam masala. Vegetariano clásico.', en: 'Cubes of paneer (Indian fresh cheese) floating in a thick pureed spinach sauce, seasoned with garlic, ginger and garam masala. A vegetarian classic.' },
  { match: 'vegetable_samosas', es: 'Triángulos de masa crujiente rellenos de papa especiada y chícharos. Fritos hasta quedar dorados, perfectos para remojar en chutney de tamarindo.', en: 'Crispy pastry triangles filled with spiced potato and peas. Deep-fried until golden, perfect for dipping in tamarind chutney.' },
  { match: 'gulab_jamun', es: 'Bolitas esponjosas de leche reducida (khoya) fritas, empapadas en un jarabe caliente de azúcar perfumado con agua de rosas y cardamomo.', en: 'Fluffy balls of reduced milk (khoya) deep-fried, soaked in a hot sugar syrup fragranced with rose water and cardamom.' },
  { match: 'mango_lassi', es: 'Bebida fría y refrescante de yogur batido con pulpa de mango dulce y un toque de cardamomo. Calma el picante de cualquier comida india.', en: 'Cold, refreshing yogurt drink blended with sweet mango pulp and a touch of cardamom. Cools the heat of any Indian meal.' },
  { match: 'tandoori_chicken', es: 'Pollo con hueso marinado en yogur, jugo de limón, jengibre y especias rojas vibrantes. Asado tradicionalmente en horno de barro tandoor.', en: 'Bone-in chicken marinated in yogurt, lemon juice, ginger and vibrant red spices. Traditionally roasted in a clay tandoor oven.' },
  { match: 'rogan_josh', es: 'Cordero cocido lentamente en una salsa aromática roja brillante de cachemira, a base de yogur, ajo y chiles kashmiri. Robusto y profundamente sabroso.', en: 'Lamb slow-cooked in a bright red aromatic Kashmiri sauce, based on yogurt, garlic and Kashmiri chiles. Robust and deeply flavorful.' },
  { match: 'chana_masala', es: 'Garbanzos tiernos cocidos en una salsa espesa de tomate con cebolla, cilantro y la mezcla de especias chana masala. Comida callejera punjabi.', en: 'Tender chickpeas cooked in a thick tomato sauce with onion, cilantro and chana masala spice blend. Punjabi street food.' },
  { match: 'dal_makhani', es: 'Lentejas negras (urad dal) y frijoles rojos cocidos toda la noche a fuego lento con mucha mantequilla y crema. El plato de lentejas más decadente de la India.', en: 'Black lentils (urad dal) and kidney beans simmered overnight on low heat with plenty of butter and cream. India\'s most decadent lentil dish.' },
  { match: 'aloo_gobi', es: 'Coliflor y papas cocidas en seco con cúrcuma, comino, cilantro y jengibre fresco. Plato casero, reconfortante y lleno del sabor de las especias enteras.', en: 'Cauliflower and potatoes dry-cooked with turmeric, cumin, coriander and fresh ginger. Homestyle, comforting and full of whole spice flavor.' }
];

async function fixAsia() {
  const pool = mysql.createPool({
    host: process.env.DB_HOST, port: parseInt(process.env.DB_PORT) || 4000,
    user: process.env.DB_USER, password: process.env.DB_PASSWORD || process.env.DB_PASS,
    database: process.env.DB_NAME, ssl: { rejectUnauthorized: false }
  });
  const conn = await pool.getConnection();
  
  const [recipes] = await conn.query('SELECT id, image_url, title FROM recipes');
  let count = 0;

  for (const r of recipes) {
    for (const mapping of descriptionsMap) {
      if (r.image_url.includes(mapping.match)) {
        const newValue = JSON.stringify({ es: mapping.es, en: mapping.en });
        await conn.query('UPDATE recipes SET description = ? WHERE id = ?', [newValue, r.id]);
        count++;
        console.log(`Corregido ID ${r.id}: ${r.title} -> Match: ${mapping.match}`);
        break;
      }
    }
  }

  console.log(`\n🎉 MEGA-PARCHE ASIA APLICADO: ${count} descripciones de China, Japón, Tailandia e India reasignadas correctamente.`);
  conn.release(); pool.end();
}
fixAsia();
