import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const descriptionsMap = [
  // MEXICO
  { match: 'torta_ahogada', es: 'Pan birote salado crujiente relleno de carnitas de cerdo, sumergido completamente en salsa picante de chile de árbol y tomate. El remedio tapatío por excelencia.', en: 'Crusty salty birote bread filled with pork carnitas, completely submerged in spicy arbol chile and tomato sauce. The ultimate cure from Guadalajara.' },
  { match: 'tacos_pastor', es: 'Tortillas de maíz rellenas de carne al pastor marinada en achiote y chiles, asada en trompo vertical. Servidos con piña, cilantro, cebolla y salsa verde.', en: 'Corn tortillas filled with al pastor meat marinated in achiote and chiles, roasted on a vertical spit. Served with pineapple, cilantro, onion and green salsa.' },
  { match: 'mexico_mole', es: 'Salsa espesa y compleja hecha con más de 20 ingredientes: chiles secos, chocolate, especias y semillas. Bañando piezas de pollo o guajolote — el plato barroco de Puebla.', en: 'Thick, complex sauce made with over 20 ingredients: dried chiles, chocolate, spices and seeds. Bathing chicken or turkey pieces — the baroque dish of Puebla.' },
  { match: 'enchiladas_suizas', es: 'Tortillas de maíz bañadas en salsa verde cremosa, rellenas de pollo deshebrado y gratinadas con queso suizo derretido. Tradición mexicana con un toque europeo.', en: 'Corn tortillas bathed in creamy green sauce, filled with shredded chicken and gratinated with melted Swiss cheese. Mexican tradition with a European touch.' },
  { match: 'mexico_pozole', es: 'Caldo rojo intenso con chiles guajillo y ancho, granos de maíz cacahuazintle y carne de cerdo. Se sirve con lechuga, rábano, orégano y limón. La sopa festiva de México.', en: 'Deep red broth with guajillo and ancho chiles, hominy corn and pork. Served with lettuce, radish, oregano and lime. Mexico\'s festive soup.' },
  { match: 'mexico_cochinita', es: 'Carne de cerdo marinada en achiote y naranja agria, envuelta en hojas de plátano y cocida lentamente bajo tierra. Se sirve con cebolla morada encurtida.', en: 'Pork marinated in achiote and sour orange, wrapped in banana leaves and slow-cooked underground. Served with pickled red onions.' },
  { match: 'chiles_nogada', es: 'Chile poblano relleno de picadillo de carne con frutas, capeado en huevo batido y frito. Bañado en salsa de nogada (nuez de castilla) y granada. Los colores de México.', en: 'Poblano chile stuffed with meat picadillo and fruits, coated in whipped egg batter and fried. Bathed in nogada (walnut cream) sauce and pomegranate. The colors of Mexico.' },
  { match: 'mexico_tamales', es: 'Masa de maíz nixtamalizado rellena de diversos guisados, envuelta en hoja de plátano o maíz y cocida al vapor. El regalo envuelto de la cocina mexicana.', en: 'Nixtamalized corn dough filled with various stews, wrapped in banana or corn husk and steamed. The wrapped gift of Mexican cuisine.' },
  { match: 'mexico_carnitas', es: 'Trozos de cerdo cocidos lentamente en su propia grasa con naranja y especias hasta quedar dorados y crujientes. El rey de la taquería mexicana.', en: 'Pork pieces slow-cooked in their own fat with orange and spices until golden and crispy. The king of the Mexican taquería.' },
  { match: 'sopa_tortilla', es: 'Caldo de tomate con tiras de tortilla de maíz frita, chile pasilla, aguacate, queso panela y crema. Texturas crujientes y reconfortantes en cada cucharada.', en: 'Tomato broth with crispy corn tortilla strips, pasilla chile, avocado, panela cheese and cream. Crispy and comforting textures in every spoonful.' },
  { match: 'guacamole', es: 'Aguacate machacado con trozos, mezclado con tomate, cebolla, chile serrano, cilantro y limón. Preparado en molcajete — la salsa mexicana más famosa del mundo.', en: 'Mashed avocado with chunks, mixed with tomato, onion, serrano chile, cilantro and lime. Made in a molcajete — the most famous Mexican salsa in the world.' },
  { match: 'arroz_con_leche', es: 'Arroz cocido lentamente en leche con canela, vainilla y azúcar hasta quedar cremoso y perfumado. Postre casero mexicano que sabe a hogar y abuela.', en: 'Rice slowly simmered in milk with cinnamon, vanilla and sugar until creamy and fragrant. Homestyle Mexican dessert that tastes like home.' },
  { match: 'flan_cajeta', es: 'Flan cremoso de huevo bañado en cajeta (dulce de leche de cabra) con caramelo dorado. La textura sedosa y el sabor acaramelado lo hacen irresistible.', en: 'Creamy egg flan bathed in cajeta (goat milk caramel) with golden caramel. The silky texture and caramel flavor make it irresistible.' },
  { match: 'pan_muerto', es: 'Pan dulce esponjoso con forma de domo y decoración en forma de huesos, aromatizado con azahar y anís. Se prepara para honrar a los difuntos el 1 y 2 de noviembre.', en: 'Fluffy sweet bread shaped as a dome with bone-shaped decorations, flavored with orange blossom and anise. Made to honor the deceased on November 1st and 2nd.' },
  { match: 'chilaquiles', es: 'Totopos de maíz crujientes bañados en salsa roja o verde, coronados con crema, queso fresco, cebolla y pollo deshebrado. El desayuno de campeones.', en: 'Crispy corn tortilla chips bathed in red or green salsa, topped with cream, fresh cheese, onion and shredded chicken. The breakfast of champions.' },
  { match: 'aguachile', es: 'Camarones crudos "cocidos" en jugo de limón con chile serrano, pepino, cebolla morada y cilantro. Picante, ácido y refrescante — ceviche sinaloense con actitud.', en: 'Raw shrimp "cooked" in lime juice with serrano chile, cucumber, red onion and cilantro. Spicy, tangy and refreshing — Sinaloan ceviche with attitude.' },
  { match: 'esquites', es: 'Granos de elote tierno hervidos con epazote y tuétano de res, servidos en vaso con mayonesa, queso rallado, chile en polvo y limón. El antojito callejero definitivo.', en: 'Tender corn kernels boiled with epazote and beef bone marrow, served in a cup with mayo, grated cheese, chili powder and lime. The definitive street food.' },
  { match: 'gorditas', es: 'Masa de maíz redonda y gruesa, frita o al comal, abierta por la mitad y rellena de chicharrón prensado, queso y salsa. Un bocado contundente y delicioso.', en: 'Thick, round corn masa, fried or griddled, split open and filled with pressed pork cracklings, cheese and salsa. A hearty and delicious bite.' },
  { match: 'sopes', es: 'Masa de maíz gruesa pellizcada con bordes levantados, cubierta con frijoles, chorizo, crema, lechuga, queso y salsa. Antojito callejero del centro de México.', en: 'Thick pinched corn masa with raised edges, topped with beans, chorizo, cream, lettuce, cheese and salsa. Street food snack from central Mexico.' },
  { match: 'tacos_suadero', es: 'Tacos de carne de suadero (falda de res) cocida lentamente en comal con grasa hasta quedar tierna y dorada. Servidos con cilantro, cebolla y salsa taquera.', en: 'Tacos with suadero meat (beef flank) slow-cooked on a griddle with fat until tender and golden. Served with cilantro, onion and taquera salsa.' },
  { match: 'camarones_diabla', es: 'Camarones salteados en salsa de chiles guajillo, morita y de árbol con mantequilla y ajo. Extremadamente picantes, rojos y adictivos.', en: 'Shrimp sautéed in guajillo, morita and de arbol chile sauce with butter and garlic. Extremely spicy, red and addictive.' },
  { match: 'mexico_ceviche', es: 'Cubos de pescado blanco fresco "cocidos" en jugo de limón con cebolla morada, chile, cilantro y tomate. Ácido, fresco y marino — la costa en un bol.', en: 'Fresh white fish cubes "cooked" in lime juice with red onion, chile, cilantro and tomato. Tangy, fresh and marine — the coast in a bowl.' },
  { match: 'barbacoa', es: 'Borrego cocido durante horas en pencas de maguey o envuelto en hojas, hasta que la carne se deshebra con los dedos. Jugosa y perfumada — la fiesta mexicana dominical.', en: 'Lamb slow-cooked for hours in agave leaves or wrapped in husks, until the meat shreds with your fingers. Juicy and fragrant — the Sunday Mexican feast.' },
  { match: 'flautas', es: 'Tortillas de maíz rellenas de pollo deshebrado, enrolladas y fritas hasta quedar crujientes como flautas. Coronadas con lechuga, crema, queso y salsa.', en: 'Corn tortillas filled with shredded chicken, rolled and fried until crispy like flutes. Topped with lettuce, cream, cheese and salsa.' },
  { match: 'huevos_rancheros', es: 'Huevos estrellados sobre tortilla de maíz frita, bañados en salsa ranchera roja picante. Servidos con frijoles refritos a un lado. El desayuno del campo.', en: 'Fried eggs over a crispy corn tortilla, bathed in spicy red ranchera sauce. Served with refried beans on the side. The countryside breakfast.' },
  { match: 'menudo', es: 'Caldo rojo intenso de estómago de res (pancita) cocido durante horas con chiles guajillo y ancho, orégano y cebolla. Se come con limón, orégano y chile picado.', en: 'Deep red broth of beef stomach (tripe) slow-cooked for hours with guajillo and ancho chiles, oregano and onion. Eaten with lime, oregano and chopped chile.' },
  { match: 'quesadillas', es: 'Tortillas de maíz hechas a mano rellenas de queso Oaxaca fundido y guisados como flor de calabaza o huitlacoche, cocidas al comal. Simples y deliciosas.', en: 'Handmade corn tortillas filled with melted Oaxaca cheese and stews like squash blossom or huitlacoche, cooked on a griddle. Simple and delicious.' },
  { match: 'tlayuda', es: 'Tortilla de maíz gigante y crujiente de Oaxaca cubierta con frijoles negros, asiento (grasa de cerdo), tasajo o cecina, quesillo, lechuga y salsa. La pizza oaxaqueña.', en: 'Giant, crispy corn tortilla from Oaxaca topped with black beans, pork fat, cured beef, string cheese, lettuce and salsa. The Oaxacan pizza.' },

  // USA
  { match: 'hamburguesa_bacon', es: 'La hamburguesa americana clásica: carne de res jugosa aplastada a la parrilla (smash), queso cheddar derretido y tocino crujiente en un pan brioche tostado.', en: 'The classic American burger: juicy smashed beef patty on the grill, melted cheddar cheese and crispy bacon on a toasted brioche bun.' },
  { match: 'fried_chicken', es: 'Pollo marinado en buttermilk y empanizado con harina especiada, frito dos veces hasta quedar extra crujiente por fuera y jugosísimo por dentro. El soul food del sur americano.', en: 'Chicken marinated in buttermilk and coated in seasoned flour, double-fried until extra crispy outside and incredibly juicy inside. Southern American soul food.' },
  { match: 'texas_brisket', es: 'Tiras de pechuga de res (brisket) ahumada durante 12-14 horas a baja temperatura hasta que la grasa se derrite y la carne se corta como mantequilla. BBQ texano puro.', en: 'Beef brisket smoked for 12-14 hours at low temperature until the fat renders and the meat cuts like butter. Pure Texas BBQ.' },
  { match: 'mac_cheese', es: 'Pasta de codo horneada en una salsa cremosa de tres quesos (cheddar, gruyère y parmesano) con costra dorada de pan rallado. El comfort food americano definitivo.', en: 'Elbow pasta baked in a creamy three-cheese sauce (cheddar, gruyère and parmesan) with a golden breadcrumb crust. The definitive American comfort food.' },
  { match: 'cheesecake_ny', es: 'Cheesecake denso y cremoso de queso crema sobre base de galleta graham, horneado en baño maría. La textura aterciopelada que hizo famosa a Nueva York.', en: 'Dense, creamy cream cheese cheesecake on a graham cracker crust, baked in a water bath. The velvety texture that made New York famous.' },
  { match: 'buffalo_wings', es: 'Alitas de pollo fritas ultra crujientes bañadas en salsa de mantequilla y cayena picante. Servidas con apio y aderezo blue cheese. Nacidas en Buffalo, NY.', en: 'Ultra-crispy fried chicken wings tossed in spicy cayenne butter sauce. Served with celery and blue cheese dressing. Born in Buffalo, NY.' },
  { match: 'philly_cheesesteak', es: 'Sándwich de carne de res cortada muy fina a la plancha, cebolla caramelizada y abundante queso derretido (provolone o Cheez Whiz) en pan hoagie. El orgullo de Filadelfia.', en: 'Sandwich with thinly sliced grilled beef, caramelized onions and abundant melted cheese (provolone or Cheez Whiz) on a hoagie roll. The pride of Philadelphia.' },
  { match: 'pulled_pork', es: 'Sándwich de cerdo deshebrado ahumado lentamente, bañado en salsa vinagreta de Carolina y coronado con coleslaw cremoso. Servido en pan brioche suave.', en: 'Pulled pork sandwich slowly smoked, dressed in Carolina vinegar sauce and topped with creamy coleslaw. Served on a soft brioche bun.' },
  { match: 'lobster_roll', es: 'Panecillo tostado en mantequilla relleno de carne de langosta de Maine fresca, mezclada con un toque de mayonesa, limón y cebollín. Lujo simple del noreste americano.', en: 'Butter-toasted roll stuffed with fresh Maine lobster meat, tossed with a touch of mayo, lemon and chives. Simple luxury from the American northeast.' },
  { match: 'biscuits_gravy', es: 'Panecillos (biscuits) sureños tiernos y hojaldrados cubiertos con una salsa espesa y cremosa (gravy) con trozos de salchicha de cerdo. El desayuno reconfortante del sur.', en: 'Tender and flaky Southern biscuits covered in a thick and creamy sausage gravy. The comforting Southern breakfast.' },
  { match: 'pumpkin_pie', es: 'Pay de calabaza especiada con canela, nuez moscada y jengibre sobre base de masa crujiente. El postre obligatorio de Thanksgiving en cada mesa americana.', en: 'Spiced pumpkin pie with cinnamon, nutmeg and ginger on a crispy pie crust. The mandatory Thanksgiving dessert on every American table.' },
  { match: 'clam_bake', es: 'Festín costero cocinado en un hoyo en la playa con algas: langosta, almejas, mejillones, maíz, papas y salchichas. La tradición veraniega de Nueva Inglaterra.', en: 'Coastal feast cooked in a beachside pit with seaweed: lobster, clams, mussels, corn, potatoes and sausages. New England\'s summer tradition.' },
  { match: 'costillas_bbq', es: 'Costillas de cerdo ahumadas lentamente durante horas con madera de nogal, bañadas en salsa BBQ dulce y ahumada. La carne se despega del hueso con un tirón.', en: 'Pork ribs slow-smoked for hours over hickory wood, basted in sweet and smoky BBQ sauce. The meat pulls clean off the bone.' },
  { match: 'clam_chowder', es: 'Sopa espesa de almejas con papas, tocino, cebolla y crema en un bol de pan sourdough. El clásico que calienta los inviernos de Nueva Inglaterra desde 1800.', en: 'Thick clam chowder with potatoes, bacon, onion and cream in a sourdough bread bowl. The classic that has warmed New England winters since 1800.' },
  { match: 'jambalaya', es: 'Jambalaya cajún con arroz, salchicha andouille, camarones, pollo y la santísima trinidad (apio, pimiento, cebolla). Un solo sartén con todo el sabor de Louisiana.', en: 'Cajun jambalaya with rice, andouille sausage, shrimp, chicken and the holy trinity (celery, bell pepper, onion). One pan with all the flavor of Louisiana.' },
  { match: 'hot_dog_ny', es: 'Salchicha de res en pan suave cubierta con mostaza amarilla, chucrut, salsa de tomate y cebolla crujiente frita. El hot dog neoyorquino de los carritos callejeros.', en: 'Beef frankfurter in a soft bun topped with yellow mustard, sauerkraut, tomato sauce and crispy fried onions. The New York street cart hot dog.' },
  { match: 'pancakes', es: 'Pancakes esponjosos y gruesos apilados en torre, bañados en maple syrup real y coronados con mantequilla y blueberries frescos. El desayuno americano por excelencia.', en: 'Thick fluffy pancakes stacked high, drizzled with real maple syrup and topped with butter and fresh blueberries. The quintessential American breakfast.' },
  { match: 'cobb_salad', es: 'Ensalada abundante con pollo asado, tocino crujiente, huevo duro, aguacate, queso azul, tomate y maíz, en filas ordenadas sobre lechuga. Nacida en Hollywood.', en: 'Abundant salad with grilled chicken, crispy bacon, hard-boiled egg, avocado, blue cheese, tomato and corn, arranged in rows over lettuce. Born in Hollywood.' },
  { match: 'meatloaf', es: 'Pan de carne molida mezclada con cebolla, pan rallado, huevo y ketchup, horneado en forma de barra con glaseado de ketchup dulce. Comfort food americano clásico.', en: 'Meatloaf mixed with onion, breadcrumbs, egg and ketchup, baked in a loaf shape with a sweet ketchup glaze. Classic American comfort food.' },
  { match: 'apple_pie', es: 'Rebanada generosa de apple pie con manzanas Granny Smith especiadas con canela y nuez moscada, entre dos capas de masa mantequillosa y dorada. América en un plato.', en: 'Generous slice of apple pie with Granny Smith apples spiced with cinnamon and nutmeg, between two layers of buttery golden crust. America on a plate.' },
  { match: 'brownie', es: 'Brownie denso y fudgy con chocolate oscuro, centro húmedo y costra crackelada. No es un pastel — es una experiencia de chocolate concentrado.', en: 'Dense, fudgy brownie with dark chocolate, moist center and crackled crust. Not a cake — it\'s a concentrated chocolate experience.' },
  { match: 'cornbread', es: 'Pan de maíz esponjoso y ligeramente dulce, horneado en sartén de hierro fundido hasta crear una costra dorada. El acompañamiento perfecto para chili o barbacoa.', en: 'Fluffy and slightly sweet cornbread, baked in a cast-iron skillet until a golden crust forms. The perfect side for chili or barbecue.' }
];

async function fixAll() {
  const pool = mysql.createPool({
    host: process.env.DB_HOST, port: parseInt(process.env.DB_PORT) || 4000,
    user: process.env.DB_USER, password: process.env.DB_PASSWORD || process.env.DB_PASS,
    database: process.env.DB_NAME, ssl: { rejectUnauthorized: false }
  });
  const conn = await pool.getConnection();
  
  const [recipes] = await conn.query('SELECT id, image_url, title FROM recipes');
  let count = 0;

  for (const r of recipes) {
    for (const mapping of descriptionsMap) {
      if (r.image_url.includes(mapping.match)) {
        const newValue = JSON.stringify({ es: mapping.es, en: mapping.en });
        await conn.query('UPDATE recipes SET description = ? WHERE id = ?', [newValue, r.id]);
        count++;
        console.log(`Corregido ID ${r.id}: ${r.title} -> Match: ${mapping.match}`);
        break;
      }
    }
  }

  console.log(`\n🎉 MEGA-PARCHE APLICADO: ${count} descripciones de USA y México reasignadas correctamente basándose en el título real de la imagen.`);
  conn.release(); pool.end();
}
fixAll();
