import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const descriptionsMap = [
  // ITALY
  { match: 'pizza_margarita', es: 'La pizza en su forma más pura: masa fina y elástica cubierta con tomate San Marzano, mozzarella fresca, hojas de albahaca y aceite de oliva virgen extra.', en: 'Pizza in its purest form: thin, chewy dough topped with San Marzano tomatoes, fresh mozzarella, basil leaves and extra virgin olive oil.' },
  { match: 'risotto', es: 'Arroz arborio tostado y cocido lentamente con caldo hirviendo, vino blanco, mantequilla y abundante queso parmesano, creando una textura increíblemente cremosa.', en: 'Arborio rice toasted and slowly cooked with boiling broth, white wine, butter and abundant parmesan cheese, creating an incredibly creamy texture.' },
  { match: 'tiramisu', es: 'Capas de bizcochos savoiardi empapados en espresso fuerte, alternadas con una crema sedosa de mascarpone y espolvoreadas con cacao puro. El postre italiano definitivo.', en: 'Layers of espresso-soaked savoiardi biscuits, alternating with a silky mascarpone cream and dusted with pure cocoa. The definitive Italian dessert.' },
  { match: 'gnocchi', es: 'Ñoquis suaves de papa hechos a mano, servidos con salsa pomodoro rústica, pesto genovés o simplemente con mantequilla y salvia. Almohadas de sabor.', en: 'Soft, handmade potato gnocchi, served with rustic pomodoro sauce, Genoese pesto or simply with butter and sage. Pillows of flavor.' },
  { match: 'gelato', es: 'Helado italiano artesanal con base de crema pastelera, leche y sabores naturales intensos (pistacho, avellana, chocolate). Más denso, suave y menos frío que el helado común.', en: 'Artisanal Italian ice cream made with a custard base, milk and intense natural flavors (pistachio, hazelnut, chocolate). Denser, softer and less cold than regular ice cream.' },
  { match: 'cannoli', es: 'Tubos de masa crujiente frita rellenos de crema de ricotta dulce, decorados con chispas de chocolate, pistachos triturados o cáscara de naranja confitada. El dulce siciliano.', en: 'Crispy fried dough tubes filled with sweet ricotta cream, decorated with chocolate chips, crushed pistachios or candied orange peel. The Sicilian sweet.' },
  { match: 'focaccia', es: 'Pan plano italiano esponjoso y aceitoso, con hoyuelos hechos con los dedos, cubierto de sal gruesa y hojas de romero fresco. Perfecto para mojar en aceite de oliva.', en: 'Spongy and oily Italian flatbread, dimpled with fingers, topped with coarse salt and fresh rosemary leaves. Perfect for dipping in olive oil.' },
  { match: 'ossobuco', es: 'Corte de caña de ternera con hueso y tuétano, estofado lentamente en vino blanco, caldo y verduras, servido tradicionalmente con gremolata cítrica y risotto amarillo.', en: 'Veal shank with bone and marrow, slowly braised in white wine, broth and vegetables, traditionally served with citrus gremolata and yellow risotto.' },
  { match: 'carbonara', es: 'Spaghetti con salsa de yemas de huevo, pecorino romano, pimienta negra y trozos crujientes de guanciale (papada de cerdo). Cremosa sin usar una gota de nata.', en: 'Spaghetti with a sauce of egg yolks, pecorino romano, black pepper and crispy pieces of guanciale (pork jowl). Creamy without a drop of heavy cream.' },
  { match: 'arancini', es: 'Bolas de arroz rellenas de ragú y mozzarella, empanizadas y fritas hasta dorar. Su nombre significa "pequeñas naranjas" debido a su color crujiente.', en: 'Rice balls stuffed with ragù and mozzarella, breaded and fried until golden. Their name means "little oranges" due to their crispy color.' },
  { match: 'bruschetta', es: 'Rebanadas de pan rústico tostado frotadas con ajo, rociadas con aceite de oliva y cubiertas con dados de tomate fresco y albahaca.', en: 'Slices of toasted rustic bread rubbed with garlic, drizzled with olive oil and topped with diced fresh tomato and basil.' },
  { match: 'cacio_e_pepe', es: 'Pasta con solo dos ingredientes de sabor: pecorino romano y abundante pimienta negra. La técnica de emulsionar el queso con el agua de cocción crea la magia.', en: 'Pasta with only two flavor ingredients: pecorino romano and abundant black pepper. The technique of emulsifying cheese with pasta water creates the magic.' },
  { match: 'calzone', es: 'Masa de pizza plegada sobre sí misma rellena de mozzarella, ricotta, salami y salsa de tomate, horneada hasta inflarse y dorarse. Una pizza en forma de empanada gigante.', en: 'Pizza dough folded over itself filled with mozzarella, ricotta, salami and tomato sauce, baked until puffed and golden. A giant empanada-shaped pizza.' },
  { match: 'carpaccio', es: 'Láminas ultrafinas de res cruda de primera calidad, servidas frías con escamas de queso parmesano, rúcula, alcaparras, aceite de oliva y limón.', en: 'Paper-thin slices of premium raw beef, served cold with shaved parmesan cheese, arugula, capers, olive oil and lemon.' },
  { match: 'fettuccine_alfredo', es: 'Fettuccine bañados en una salsa cremosa de mantequilla y parmesano reggiano derretidos, que emulsionan con el agua de la pasta. Nacido en Roma en 1914.', en: 'Fettuccine bathed in a creamy sauce of melted butter and parmigiano reggiano, emulsified with pasta water. Born in Rome in 1914.' },
  { match: 'melanzane', es: 'Capas de berenjena frita, salsa de tomate casera y abundante queso parmesano y mozzarella, horneadas hasta burbujear. Un plato vegetariano contundente y delicioso.', en: 'Layers of fried eggplant, homemade tomato sauce and abundant parmesan and mozzarella cheese, baked until bubbly. A hearty and delicious vegetarian dish.' },
  { match: 'minestrone', es: 'Sopa rústica italiana cargada de verduras de temporada, frijoles y pasta pequeña o arroz. Espesa, reconfortante y saludable.', en: 'Rustic Italian soup loaded with seasonal vegetables, beans and small pasta or rice. Thick, comforting and healthy.' },
  { match: 'panettone', es: 'Pan dulce alto y esponjoso con frutas confitadas y pasas, que requiere días de fermentación lenta. El sabor inconfundible de la Navidad italiana.', en: 'Tall and fluffy sweet bread with candied fruits and raisins, requiring days of slow fermentation. The unmistakable taste of Italian Christmas.' },
  { match: 'panna_cotta', es: 'Crema de nata cocida con azúcar y vainilla, cuajada ligeramente con gelatina para que tiemble al tocarla, servida fría con coulis de frutos rojos.', en: 'Heavy cream cooked with sugar and vanilla, lightly set with gelatin so it trembles when touched, served cold with red berry coulis.' },
  { match: 'polenta', es: 'Polenta de maíz cocida lentamente hasta quedar cremosa, servida con un abundante ragú de carne encima. La comida reconfortante del norte de Italia.', en: 'Corn polenta slowly cooked until creamy, served with a rich meat ragù on top. The comfort food of Northern Italy.' },
  { match: 'cacciatore', es: 'Pollo troceado dorado en sartén y cocido en salsa "estilo cazador" con tomate, cebolla, champiñones, pimientos y vino tinto o blanco.', en: 'Chicken pieces browned in a pan and cooked "hunter style" in a sauce of tomatoes, onions, mushrooms, bell peppers and red or white wine.' },
  { match: 'prosciutto_melone', es: 'Láminas de prosciutto crudo curado envolviendo gajos de melón cantalupo dulce y jugoso. El aperitivo italiano perfecto de verano.', en: 'Slices of cured raw prosciutto wrapping wedges of sweet, juicy cantaloupe melon. The perfect Italian summer appetizer.' },
  { match: 'lasagna_casera', es: 'Capas de pasta ancha con ragú boloñés de carne cocido durante horas, bechamel cremosa y parmesano gratinado. El plato dominical de Emilia-Romaña.', en: 'Layers of wide pasta with slow-cooked meat bolognese ragù, creamy béchamel and gratinated parmesan. The Sunday dish of Emilia-Romagna.' },
  { match: 'fiorentina', es: 'Chuletón de ternera chianina de 4cm de grosor, asado a la brasa muy poco hecho, sazonado solo con sal, pimienta y aceite de oliva.', en: '4cm thick chianina beef T-bone steak, grilled very rare, seasoned only with salt, pepper and olive oil.' },
  { match: 'ravioles', es: 'Pasta fresca rellena de ricotta cremosa, espinacas y nuez moscada, servida con salsa de mantequilla y salvia dorada. La delicadeza de la pasta rellena.', en: 'Fresh pasta filled with creamy ricotta, spinach and nutmeg, served with a golden butter and sage sauce. The delicacy of stuffed pasta.' },
  { match: 'affogato', es: 'Una bola de gelato de vainilla "ahogada" en un shot de espresso caliente. El postre-café italiano de dos ingredientes que se prepara en 10 segundos.', en: 'A scoop of vanilla gelato "drowned" in a hot espresso shot. The two-ingredient Italian coffee-dessert prepared in 10 seconds.' },
  { match: 'biscotti', es: 'Galletas italianas crujientes horneadas dos veces con almendras tostadas, perfectas para sumergir en vino Santo o café al final de la comida.', en: 'Crunchy Italian cookies baked twice with toasted almonds, perfect for dipping in Vin Santo or coffee at the end of a meal.' },
  { match: 'caprese', es: 'Rodajas de tomate fresco, mozzarella di bufala y hojas de albahaca, rociadas con aceite de oliva virgen extra y sal. Los colores de la bandera italiana.', en: 'Slices of fresh tomato, buffalo mozzarella and basil leaves, drizzled with extra virgin olive oil and salt. The colors of the Italian flag.' },
  { match: 'panzanella', es: 'Ensalada toscana de pan duro remojado en vinagre, mezclado con tomates maduros, cebolla roja, pepino y albahaca.', en: 'Tuscan salad of stale bread soaked in vinegar, mixed with ripe tomatoes, red onion, cucumber and basil.' },
  { match: 'sfogliatella', es: 'Masa hojaladrada en forma de concha rellena de crema de ricotta dulce con toques de naranja. Increíblemente crujiente en cada capa.', en: 'Shell-shaped flaky pastry filled with sweet ricotta cream with hints of orange. Incredibly crispy on every layer.' },
  { match: 'bolognese', es: 'El plato de pasta más famoso del mundo: spaghetti con ragú boloñés de carne cocido a fuego lento con tomate, zanahoria, apio y vino tinto.', en: 'The world\'s most famous pasta dish: spaghetti with meat bolognese ragù slow-cooked with tomato, carrot, celery and red wine.' },
  { match: 'tortellini', es: 'Pasta rellena en forma de anillo con carne y parmesano, servida en un caldo de res cristalino y perfumado. El abrazo italiano en forma de sopa.', en: 'Ring-shaped stuffed pasta with meat and parmesan, served in a crystal-clear, fragrant beef broth. The Italian hug in soup form.' },
  { match: 'milanese', es: 'Milanesa de ternera empanizada en pan rallado fino y frita en mantequilla clarificada hasta quedar dorada y crujiente.', en: 'Breaded veal cutlet coated in fine breadcrumbs and fried in clarified butter until golden and crispy.' },
  { match: 'zabaione', es: 'Crema caliente y espumosa de yemas batidas con azúcar y vino dulce Marsala al baño maría. Suave, etérea y reconfortante.', en: 'Hot, frothy cream of egg yolks whipped with sugar and sweet Marsala wine in a bain-marie. Soft, ethereal and comforting.' },
  { match: 'zeppole', es: 'Bolitas de masa choux fritas, rellenas de crema pastelera y coronadas con una cereza amarena confitada.', en: 'Fried choux pastry balls, filled with pastry cream and topped with a candied amarena cherry.' },
  
  // FRANCE
  { match: 'ratatouille', es: 'Guiso provenzal de verduras mediterráneas (berenjena, calabacín, tomate, pimiento) cocinadas lentamente con aceite de oliva y hierbas provenzales.', en: 'Provençal stew of Mediterranean vegetables (eggplant, zucchini, tomato, bell pepper) slow-cooked with olive oil and herbes de Provence.' },
  { match: 'quiche_lorraine', es: 'Tarta salada de masa quebrada rellena de una mezcla batida de huevos, crema espesa, panceta ahumada y queso gruyère, horneada hasta dorar.', en: 'Savory tart of shortcrust pastry filled with a beaten mixture of eggs, heavy cream, smoked bacon and gruyère cheese, baked until golden.' },
  { match: 'coq_au_vin', es: 'Pollo troceado cocido lentamente en vino tinto de Borgoña con cebollitas perla, champiñones y tocino. El clásico guiso rústico francés.', en: 'Chicken pieces slow-cooked in Burgundy red wine with pearl onions, mushrooms and bacon. The classic rustic French stew.' },
  { match: 'boeuf_bourguignon', es: 'Estofado de res cocido durante horas en vino tinto con zanahorias, cebollitas y bouquet garni hasta que la carne se deshace.', en: 'Beef stew slow-cooked for hours in red wine with carrots, pearl onions and bouquet garni until the meat falls apart.' },
  { match: 'bouillabaisse', es: 'Sopa de pescadores marsellesa con múltiples pescados de roca, azafrán, hinojo y tomate, servida con tostadas de pan y salsa rouille picante.', en: 'Marseille fisherman\'s soup with multiple rockfish, saffron, fennel and tomato, served with toasted bread and spicy rouille sauce.' },
  { match: 'confit_canard', es: 'Muslo de pato curado en sal y especias, cocido lentamente en su propia grasa y dorado en el horno para lograr una piel crujientísima.', en: 'Duck leg cured in salt and spices, slow-cooked in its own fat and browned in the oven to achieve an ultra-crispy skin.' },
  { match: 'croissants', es: 'Masa laminada con mantequilla francesa doblada en múltiples capas finas, horneada hasta obtener una forma de media luna aireada y crujiente.', en: 'French butter laminated dough folded into multiple thin layers, baked to obtain an airy and crispy crescent shape.' },
  { match: 'macarons', es: 'Galletas de merengue de almendras con superficie lisa y "pie" rizado, unidas por ganache o crema. Elegancia francesa de un solo bocado.', en: 'Almond meringue cookies with a smooth surface and ruffled "foot", joined by ganache or cream. French elegance in a single bite.' },
  { match: 'mousse_chocolate', es: 'Chocolate negro derretido y combinado con claras batidas a punto de nieve para lograr una textura etérea, espumosa y llena de aire.', en: 'Dark chocolate melted and folded into stiff egg whites to achieve an ethereal, frothy and airy texture.' },
  { match: 'creme_brulee', es: 'Crema de vainilla horneada a baja temperatura hasta cuajar suavemente, coronada con una costra de azúcar dura y quebradiza quemada con soplete.', en: 'Vanilla custard baked at low temperature until softly set, topped with a hard, brittle sugar crust burnt with a blowtorch.' },
  { match: 'cassoulet', es: 'Guiso rústico de Languedoc con judiones blancos, salchichas de Toulouse, cerdo y confit de pato, horneado lentamente hasta formar una costra espesa.', en: 'Rustic Languedoc stew with white beans, Toulouse sausages, pork and duck confit, slow-baked until a thick crust forms.' },
  { match: 'steak_frites', es: 'Filete grueso de carne de res sellado en sartén de hierro, servido rojo por dentro y acompañado de abundantes y crujientes papas fritas.', en: 'Thick beef steak seared in an iron skillet, served rare inside and accompanied by abundant crispy French fries.' },
  { match: 'coquilles_saint_jacques', es: 'Vieiras doradas en mantequilla con costra caramelizada, servidas a menudo en su propia concha con salsa de crema blanca o gratén.', en: 'Scallops browned in butter with a caramelized crust, often served in their own shell with a white cream sauce or gratin.' },
  { match: 'croque_monsieur', es: 'Sándwich de pan de molde con jamón y queso gruyère, coronado con salsa bechamel extra y gratinado en el horno hasta burbujear.', en: 'Sandwich bread with ham and gruyère cheese, topped with extra béchamel sauce and gratinated in the oven until bubbly.' },
  { match: 'tarte_tatin', es: 'Tarta invertida de manzanas caramelizadas en mantequilla y azúcar, cubierta con masa hojaldre y horneada antes de voltearse caliente.', en: 'Upside-down tart of apples caramelized in butter and sugar, covered with puff pastry and baked before being flipped hot.' },
  { match: 'profiteroles', es: 'Bolitas de masa choux hueca horneada, rellenas de helado de vainilla y bañadas generosamente en salsa de chocolate negro caliente.', en: 'Hollow baked choux pastry balls, filled with vanilla ice cream and generously drizzled with hot dark chocolate sauce.' },
  { match: 'crepes_suzette', es: 'Crêpes finas flameadas en salsa de mantequilla, azúcar, jugo de naranja y licor Grand Marnier.', en: 'Thin crêpes flambéed in a sauce of butter, sugar, orange juice and Grand Marnier liqueur.' },
  { match: 'escargots', es: 'Caracoles de Borgoña al horno en sus conchas, rellenados con abundante mantequilla mezclada con ajo picado y perejil fresco.', en: 'Burgundy snails baked in their shells, stuffed with abundant butter mixed with minced garlic and fresh parsley.' },
  { match: 'soupe_oignon', es: 'Cebolla caramelizada largo rato en mantequilla, con caldo de res, vino blanco y gratinada con pan crujiente y queso gruyère derretido.', en: 'Onions caramelized for a long time in butter, with beef broth, white wine and gratinated with crusty bread and melted gruyère cheese.' },
  { match: 'salade_nicoise', es: 'Ensalada de Niza con atún, huevo duro, judías verdes, aceitunas negras, papas cocidas, tomate y anchoas, aliñada con aceite de oliva.', en: 'Niçoise salad with tuna, hard-boiled egg, green beans, black olives, boiled potatoes, tomato and anchovies, dressed with olive oil.' },
  { match: 'souffle_fromage', es: 'Suflé esponjoso y aireado de queso gruyère que sube espectacularmente en el horno gracias a las claras a punto de nieve.', en: 'Fluffy and airy gruyère cheese soufflé that rises spectacularly in the oven thanks to stiff egg whites.' },
  { match: 'pissaladiere', es: 'Coca plana de masa de pan cubierta con cebolla caramelizada, aceitunas negras enteras y anchoas, horneada hasta quedar crujiente.', en: 'Flat bread dough tart topped with caramelized onions, whole black olives and anchovies, baked until crispy.' },
  { match: 'souffle_chocolat', es: 'Suflé de chocolate negro que sube ligero y aireado, servido caliente de inmediato antes de que colapse, con el interior aún húmedo.', en: 'Dark chocolate soufflé that rises light and airy, served hot immediately before it collapses, with the inside still moist.' },
  
  // SPAIN
  { match: 'paella_valenciana', es: 'Arroz cocinado en paellera ancha con pollo, conejo, garrofón, judía verde y el inconfundible aroma, color y sabor del azafrán, con el famoso socarrat crujiente en el fondo.', en: 'Rice cooked in a wide paella pan with chicken, rabbit, lima beans, green beans and the unmistakable aroma, color and flavor of saffron, with the famous crispy socarrat at the bottom.' },
  { match: 'tortilla_patatas', es: 'Tortilla gruesa y jugosa de huevos y patatas confitadas en abundante aceite de oliva (y a menudo cebolla). El pincho más famoso de España.', en: 'Thick, juicy omelet of eggs and potatoes slowly fried in abundant olive oil (and often onion). Spain\'s most famous tapa.' },
  { match: 'gazpacho', es: 'Sopa fría de tomates maduros, pimiento, pepino, ajo, aceite de oliva y vinagre, triturada hasta quedar líquida. El refresco del verano andaluz.', en: 'Cold soup of ripe tomatoes, bell pepper, cucumber, garlic, olive oil and vinegar, blended until liquid. The refreshment of the Andalusian summer.' },
  { match: 'pulpo_gallega', es: 'Pulpo cocido y cortado en rodajas gruesas, servido sobre tabla de madera con sal gruesa, aceite de oliva virgen extra y pimentón (dulce y picante).', en: 'Boiled octopus cut into thick slices, served on a wooden board with coarse salt, extra virgin olive oil and paprika (sweet and spicy).' },
  { match: 'patatas_bravas', es: 'Cubos de papa frita crujientes bañados en salsa brava (salsa roja picante de pimentón y caldo, sin tomate). La tapa obligatoria en cualquier bar.', en: 'Crispy fried potato cubes bathed in brava sauce (spicy red sauce of paprika and broth, no tomato). The mandatory tapa in any bar.' },
  { match: 'jamon_iberico', es: 'Jamón ibérico de bellota cortado a mano en láminas finísimas y traslúcidas. Sabor umami complejo y grasa que se funde en el paladar.', en: 'Acorn-fed Iberian ham hand-carved into paper-thin, translucent slices. Complex umami flavor and fat that melts on the palate.' },
  { match: 'gambas_ajillo', es: 'Gambas enteras salteadas en abundante aceite de oliva muy caliente, láminas de ajo frito y una guindilla seca para darle chispa. Servidas hirviendo.', en: 'Whole prawns sautéed in abundant, very hot olive oil, fried garlic slices and a dried chili for a spark. Served sizzling hot.' },
  { match: 'fabada', es: 'Guiso asturiano de judiones blancos gigantes con compango (chorizo, morcilla y tocino asturianos), cocinado a fuego lento hasta que el caldo espesa.', en: 'Asturian stew of giant white beans with compango (Asturian chorizo, blood sausage and bacon), slow-cooked until the broth thickens.' },
  { match: 'crema_catalana', es: 'Crema de yemas con leche, azúcar, canela y ralladura de limón, espesada con almidón y coronada con una costra de azúcar quemada con plancha.', en: 'Egg yolk custard with milk, sugar, cinnamon and lemon zest, thickened with starch and topped with a sugar crust burnt with an iron.' },
  { match: 'churros', es: 'Masa de agua y harina extruida en forma de estrella, frita en aceite muy caliente hasta quedar crujiente. Se mojan en chocolate espeso a la taza.', en: 'Flour and water dough extruded in a star shape, deep-fried in very hot oil until crispy. Dipped in thick hot chocolate.' },
  { match: 'tarta_santiago', es: 'Tarta densa de almendras molidas sin harina de trigo, huevos y azúcar, espolvoreada con azúcar glass mostrando la Cruz de Santiago.', en: 'Dense cake of ground almonds without wheat flour, eggs and sugar, dusted with powdered sugar showing the Cross of St. James.' },
  { match: 'cocido_madrileno', es: 'Guiso madrileño de garbanzos con múltiples carnes (morcillo, tocino, gallina, chorizo), verduras y sopa de fideos, servido tradicionalmente en "tres vuelcos".', en: 'Madrid chickpea stew with multiple meats (beef shank, bacon, hen, chorizo), vegetables and noodle soup, traditionally served in "three courses".' },
  { match: 'cochinillo', es: 'Lechón entero asado lentamente en horno de leña hasta lograr una carne tan tierna que se corta con el borde de un plato, y una piel ultra crujiente.', en: 'Whole suckling pig slowly roasted in a wood-fired oven until the meat is so tender it can be cut with the edge of a plate, and an ultra-crispy skin.' },
  { match: 'bacalao_pil_pil', es: 'Lomo de bacalao confitado a baja temperatura en aceite de oliva y ajo, moviendo la cazuela para emulsionar la gelatina del pescado y crear la salsa pil-pil.', en: 'Cod loin confit at low temperature in olive oil and garlic, moving the pot to emulsify the fish gelatin and create the pil-pil sauce.' },
  { match: 'escalivada', es: 'Verduras mediterráneas (berenjena, pimiento, cebolla) asadas enteras, peladas y servidas en tiras con aceite de oliva virgen extra y sal.', en: 'Mediterranean vegetables (eggplant, bell pepper, onion) roasted whole, peeled and served in strips with extra virgin olive oil and salt.' },
  { match: 'pimientos_padron', es: 'Pimientos verdes pequeños de Padrón fritos en aceite muy caliente hasta ampollarse, espolvoreados con sal gruesa. "Unos pican y otros no".', en: 'Small green Padron peppers fried in very hot oil until blistered, dusted with coarse salt. "Some are spicy and some are not".' },
  { match: 'arroz_negro', es: 'Arroz teñido de negro intenso con tinta de calamar, cocinado con sepia, calamar y caldo de pescado. Se sirve tradicionalmente con alioli de ajo.', en: 'Rice dyed deep black with squid ink, cooked with cuttlefish, squid and fish broth. Traditionally served with garlic aioli.' },
  { match: 'calamares_romana', es: 'Anillos de calamar rebozados en harina y fritos en abundante aceite, servidos muy calientes con un gajo de limón. Famosos también en bocadillo en Madrid.', en: 'Squid rings coated in flour and fried in abundant oil, served very hot with a wedge of lemon. Also famous in a sandwich in Madrid.' },
  { match: 'salmorejo', es: 'Crema fría de tomate, pan duro, ajo, aceite de oliva y sal, mucho más espesa que el gazpacho, servida con huevo duro picado y jamón ibérico.', en: 'Cold cream of tomato, stale bread, garlic, olive oil and salt, much thicker than gazpacho, served with chopped hard-boiled egg and Iberian ham.' },
  { match: 'croquetas', es: 'Croquetas de bechamel ultracremosa con cubitos de jamón ibérico, rebozadas y fritas. Su exterior es crujiente pero el interior fluye y se deshace.', en: 'Ultra-creamy béchamel croquettes with cubes of Iberian ham, breaded and fried. The exterior is crispy but the interior flows and melts.' },
  { match: 'cordero_asado', es: 'Pierna o paletilla de cordero asada lentamente con agua, sal, ajo y manteca. Su simpleza deja brillar el potente sabor y jugosidad de la carne.', en: 'Leg or shoulder of lamb slowly roasted with water, salt, garlic and lard. Its simplicity lets the powerful flavor and juiciness of the meat shine.' },
  { match: 'pescado_frito', es: 'Boquerones, chanquetes y calamares enharinados y fritos en aceite de oliva muy caliente, servidos en cucurucho de papel con limón. El chiringuito malagueño.', en: 'Anchovies, whitebait and squid coated in flour and fried in very hot olive oil, served in a paper cone with lemon. The Malaga beach bar.' },

  // GREECE
  { match: 'moussaka', es: 'Capas de berenjena frita, carne picada de cordero con tomate y canela, coronadas con bechamel espesa y gratinada. El pastel de carne griego — sustancioso y reconfortante.', en: 'Layers of fried eggplant, minced lamb with tomato and cinnamon, topped with thick and gratinated béchamel. The Greek meat pie — hearty and comforting.' },
  { match: 'gyros', es: 'Tiras de pollo o cerdo marinadas asadas en espetón vertical, cortadas finas y envueltas en pan pita con tomate, cebolla, patatas fritas y salsa tzatziki.', en: 'Strips of marinated chicken or pork roasted on a vertical spit, thinly sliced and wrapped in pita bread with tomato, onion, fries and tzatziki sauce.' },
  { match: 'baklava', es: 'Capas de masa filo crujiente rellenas de nueces picadas, horneadas hasta dorar y bañadas en un denso jarabe de azúcar, limón y agua de azahar.', en: 'Layers of crispy phyllo dough filled with chopped walnuts, baked until golden and drenched in a dense syrup of sugar, lemon and orange blossom water.' },
  { match: 'spanakopita', es: 'Triángulos de masa filo crujiente rellenos de espinacas frescas, queso feta desmenuzado, eneldo y cebolleta. Dorados al horno — el snack griego crujiente.', en: 'Crispy phyllo dough triangles filled with fresh spinach, crumbled feta cheese, dill and scallion. Oven-baked golden — the crunchy Greek snack.' },
  { match: 'dolmades', es: 'Hojas de parra tiernas rellenas de arroz aromático con hierbas (menta, eneldo), piñones y aceite de oliva. A menudo servidas con un chorrito de limón.', en: 'Tender grape leaves stuffed with aromatic rice with herbs (mint, dill), pine nuts and olive oil. Often served with a squeeze of lemon.' },
  { match: 'tzatziki', es: 'Salsa griega espesa de yogur colado con pepino rallado, ajo, eneldo, aceite de oliva y limón. Fresca y cremosa — acompaña desde gyros hasta verduras asadas.', en: 'Thick Greek sauce of strained yogurt with grated cucumber, garlic, dill, olive oil and lemon. Fresh and creamy — accompanies anything from gyros to roasted vegetables.' },
  { match: 'pastitsio', es: 'Pasta tubular horneada con ragú de carne de res y canela, cubierta con bechamel espesa y gratinada. El primo griego de la lasaña — reconfortante y especiado.', en: 'Tubular pasta baked with beef ragù and cinnamon, covered with thick and gratinated béchamel. The Greek cousin of lasagna — comforting and spiced.' },
  { match: 'galaktoboureko', es: 'Pastel griego de crema de sémola con ralladura de naranja, horneado entre capas de masa filo crujiente y empapado en jarabe dulce caliente.', en: 'Greek semolina custard pie with orange zest, baked between layers of crispy phyllo dough and soaked in hot sweet syrup.' },
  { match: 'keftedes', es: 'Albóndigas griegas de carne de cordero y res con menta, orégano, cebolla y pan remojado, fritas hasta dorar. Servidas con tzatziki frío.', en: 'Greek meatballs of lamb and beef with mint, oregano, onion and soaked bread, fried until golden. Served with cold tzatziki.' },
  { match: 'saganaki', es: 'Bloque grueso de queso graviera o kasseri rebozado y frito en sartén, a menudo flameado con brandy en la mesa y apagado con jugo de limón fresco.', en: 'Thick block of graviera or kasseri cheese coated and pan-fried, often flambéed with brandy at the table and extinguished with fresh lemon juice.' },
  { match: 'gemista', es: 'Tomates y pimientos vaciados y rellenos de arroz con hierbas, cebolla y aceite de oliva, asados al horno hasta quedar suaves y caramelizados.', en: 'Tomatoes and bell peppers hollowed out and stuffed with herb rice, onion and olive oil, roasted in the oven until soft and caramelized.' },
  { match: 'fasolada', es: 'Sopa griega rústica de judiones blancos con tomate, zanahoria, apio y generosas cantidades de aceite de oliva. La comida nacional humilde de Grecia.', en: 'Rustic Greek soup of large white beans with tomato, carrot, celery and generous amounts of olive oil. The humble national food of Greece.' },
  { match: 'youvetsi', es: 'Ternera cocida lentamente en salsa de tomate con canela y clavo, horneada en olla de barro con pasta orzo que absorbe todos los jugos de la carne.', en: 'Beef slow-cooked in tomato sauce with cinnamon and clove, baked in a clay pot with orzo pasta that absorbs all the meat juices.' },
  { match: 'souvlaki', es: 'Brochetas de carne de cerdo marinadas en limón, orégano y aceite de oliva, asadas a la brasa. Se sirven en plato con ensalada o en pan pita.', en: 'Pork skewers marinated in lemon, oregano and olive oil, char-grilled. Served on a plate with salad or in pita bread.' },
  { match: 'kleftiko', es: 'Pierna de cordero asada a fuego lento, marinada en ajo, limón y orégano. La carne queda tierna, jugosa y llena de sabor tradicional griego.', en: 'Slow-roasted leg of lamb, marinated in garlic, lemon and oregano. The meat is tender, juicy and full of traditional Greek flavor.' },
  { match: 'taramosalata', es: 'Dip griego cremoso de huevas de pescado (tarama) batidas con pan remojado, aceite de oliva, jugo de limón y cebolla. Rosado, suave y con profundo sabor a mar.', en: 'Creamy Greek dip of fish roe (tarama) whipped with soaked bread, olive oil, lemon juice and onion. Pink, smooth and with a deep sea flavor.' },
  { match: 'loukoumades', es: 'Bolitas de masa frita esponjosas bañadas en miel caliente y espolvoreadas con canela y nueces picadas. El bocado dulce más antiguo de Grecia.', en: 'Fluffy fried dough balls drenched in hot honey and sprinkled with cinnamon and chopped walnuts. Greece\'s oldest sweet bite.' },
  { match: 'greek_salad', es: 'Ensalada griega clásica con tomate, pepino, cebolla roja, aceitunas kalamata y un gran bloque de queso feta encima, aliñada con orégano y aceite de oliva.', en: 'Classic Greek salad with tomato, cucumber, red onion, kalamata olives and a large block of feta cheese on top, dressed with oregano and olive oil.' }
];

async function fixEurope() {
  const pool = mysql.createPool({
    host: process.env.DB_HOST, port: parseInt(process.env.DB_PORT) || 4000,
    user: process.env.DB_USER, password: process.env.DB_PASSWORD || process.env.DB_PASS,
    database: process.env.DB_NAME, ssl: { rejectUnauthorized: false }
  });
  const conn = await pool.getConnection();
  
  const [recipes] = await conn.query('SELECT id, image_url, title FROM recipes');
  let count = 0;

  for (const r of recipes) {
    for (const mapping of descriptionsMap) {
      if (r.image_url.includes(mapping.match)) {
        const newValue = JSON.stringify({ es: mapping.es, en: mapping.en });
        await conn.query('UPDATE recipes SET description = ? WHERE id = ?', [newValue, r.id]);
        count++;
        console.log(`Corregido ID ${r.id}: ${r.title} -> Match: ${mapping.match}`);
        break;
      }
    }
  }

  console.log(`\n🎉 MEGA-PARCHE EUROPA APLICADO: ${count} descripciones de Italia, Francia, España y Grecia reasignadas correctamente.`);
  conn.release(); pool.end();
}
fixEurope();
